<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CameraModule\CameraModule.csproj" />
		<ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
		<ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<Reference Include="LanguageManager">
			<HintPath>..\Thirddll\net48\LanguageManager.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
		<Reference Include="LanguageManager">
			<HintPath>..\Thirddll\net8\LanguageManager.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
