//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoThinkCam.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoThinkCam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 出现异常 的本地化字符串。
        /// </summary>
        public static string AppearError {
            get {
                return ResourceManager.GetString("AppearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未搜索到度申相机,搜索个数为0 的本地化字符串。
        /// </summary>
        public static string CameraNotFound {
            get {
                return ResourceManager.GetString("CameraNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 度申相机序列号: 的本地化字符串。
        /// </summary>
        public static string CameraSerialNumber {
            get {
                return ResourceManager.GetString("CameraSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机回调函数异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorCallBack {
            get {
                return ResourceManager.GetString("ErrorCallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“保存用户设置”失败 的本地化字符串。
        /// </summary>
        public static string ExcuteSaveUserSetingFail {
            get {
                return ResourceManager.GetString("ExcuteSaveUserSetingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;保存用户设置&quot;成功 的本地化字符串。
        /// </summary>
        public static string ExcuteSaveUserSetingSucess {
            get {
                return ResourceManager.GetString("ExcuteSaveUserSetingSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;上电选择用户设置”失败 的本地化字符串。
        /// </summary>
        public static string ExcuteSelectUserSetingPowerOnFail {
            get {
                return ResourceManager.GetString("ExcuteSelectUserSetingPowerOnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“上电选择用户设置USER_SET_1”成功 的本地化字符串。
        /// </summary>
        public static string ExcuteSelectUserSetingUserSet1PowerOnSucess {
            get {
                return ResourceManager.GetString("ExcuteSelectUserSetingUserSet1PowerOnSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置Gamma使能&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaEnableError {
            get {
                return ResourceManager.GetString("ExcuteSetGammaEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置Gamma使能&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaEnableFail {
            get {
                return ResourceManager.GetString("ExcuteSetGammaEnableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置Gamma使能&quot;为 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaEnableIs {
            get {
                return ResourceManager.GetString("ExcuteSetGammaEnableIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置Gamma值发生异常: 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaValueError {
            get {
                return ResourceManager.GetString("ExcuteSetGammaValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置Gamma值&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaValueFail {
            get {
                return ResourceManager.GetString("ExcuteSetGammaValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置Gamma值”为 的本地化字符串。
        /// </summary>
        public static string ExcuteSetGammaValueIs {
            get {
                return ResourceManager.GetString("ExcuteSetGammaValueIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;关闭相机&quot; 的本地化字符串。
        /// </summary>
        public static string ExecuteCloseCamera {
            get {
                return ResourceManager.GetString("ExecuteCloseCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;关闭相机&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteCloseCameraError {
            get {
                return ResourceManager.GetString("ExecuteCloseCameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“关灯”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteCloseLightFail {
            get {
                return ResourceManager.GetString("ExecuteCloseLightFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前曝光值发生异常: 的本地化字符串。
        /// </summary>
        public static string ExecuteGetExposureTimeError {
            get {
                return ResourceManager.GetString("ExecuteGetExposureTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取最大曝光值发生异常: 的本地化字符串。
        /// </summary>
        public static string ExecuteGetExposureTimeMaxError {
            get {
                return ResourceManager.GetString("ExecuteGetExposureTimeMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取最小曝光值发生异常: 的本地化字符串。
        /// </summary>
        public static string ExecuteGetExposureTimeMinError {
            get {
                return ResourceManager.GetString("ExecuteGetExposureTimeMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取增益值发生异常: 的本地化字符串。
        /// </summary>
        public static string ExecuteGetGainError {
            get {
                return ResourceManager.GetString("ExecuteGetGainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行”信号反转“ 的本地化字符串。
        /// </summary>
        public static string ExecuteLineInverter {
            get {
                return ResourceManager.GetString("ExecuteLineInverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行”信号反转“异常 的本地化字符串。
        /// </summary>
        public static string ExecuteLineInverterError {
            get {
                return ResourceManager.GetString("ExecuteLineInverterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行”信号反转“失败 的本地化字符串。
        /// </summary>
        public static string ExecuteLineInverterFail {
            get {
                return ResourceManager.GetString("ExecuteLineInverterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置输出线路发生异常: 的本地化字符串。
        /// </summary>
        public static string ExecuteLineSelectorError {
            get {
                return ResourceManager.GetString("ExecuteLineSelectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“开灯”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteOpenLightFail {
            get {
                return ResourceManager.GetString("ExecuteOpenLightFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;选择输出触发类型&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSelectOutputTriggerTypeError {
            get {
                return ResourceManager.GetString("ExecuteSelectOutputTriggerTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;选择输出触发类型&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSelectOutputTriggerTypeFail {
            get {
                return ResourceManager.GetString("ExecuteSelectOutputTriggerTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;选择输出触发类型&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSelectOutputTriggerTypeIs {
            get {
                return ResourceManager.GetString("ExecuteSelectOutputTriggerTypeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置通道1曝光值”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetChannel1ExposureTimeFail {
            get {
                return ResourceManager.GetString("ExecuteSetChannel1ExposureTimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置通道2曝光值”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetChannel2ExposureTimeFail {
            get {
                return ResourceManager.GetString("ExecuteSetChannel2ExposureTimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置通道3曝光值”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetChannel3ExposureTimeFail {
            get {
                return ResourceManager.GetString("ExecuteSetChannel3ExposureTimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置通道4曝光值”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetChannel4ExposureTimeFail {
            get {
                return ResourceManager.GetString("ExecuteSetChannel4ExposureTimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置曝光值&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetExposureTime {
            get {
                return ResourceManager.GetString("ExecuteSetExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置曝光值&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetExposureTimeError {
            get {
                return ResourceManager.GetString("ExecuteSetExposureTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置曝光值&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetExposureTimeFail {
            get {
                return ResourceManager.GetString("ExecuteSetExposureTimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 设置拍照次数为: 的本地化字符串。
        /// </summary>
        public static string ExecuteSetFrameCount {
            get {
                return ResourceManager.GetString("ExecuteSetFrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置拍照次数&quot;出现错误 的本地化字符串。
        /// </summary>
        public static string ExecuteSetFrameCountError {
            get {
                return ResourceManager.GetString("ExecuteSetFrameCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置拍照次数&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetFrameCountFail {
            get {
                return ResourceManager.GetString("ExecuteSetFrameCountFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置增益&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetGainError {
            get {
                return ResourceManager.GetString("ExecuteSetGainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置增益&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetGainFail {
            get {
                return ResourceManager.GetString("ExecuteSetGainFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置增益&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetGainIs {
            get {
                return ResourceManager.GetString("ExecuteSetGainIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置输入输出模式” 的本地化字符串。
        /// </summary>
        public static string ExecuteSetInputOutputMode {
            get {
                return ResourceManager.GetString("ExecuteSetInputOutputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置输入输出模式”异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetInputOutputModeError {
            get {
                return ResourceManager.GetString("ExecuteSetInputOutputModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行“设置输入输出模式”失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetInputOutputModeFail {
            get {
                return ResourceManager.GetString("ExecuteSetInputOutputModeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置输出持续时间&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetStrobeDurationValueError {
            get {
                return ResourceManager.GetString("ExecuteSetStrobeDurationValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置输出持续时间&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetStrobeDurationValueFail {
            get {
                return ResourceManager.GetString("ExecuteSetStrobeDurationValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置输出持续时间&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetStrobeDurationValueIs {
            get {
                return ResourceManager.GetString("ExecuteSetStrobeDurationValueIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置触发延时&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerDelayError {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerDelayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置触发延时&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerDelayFail {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerDelayFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;设置触发延时&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerDelayIs {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerDelayIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机触发模式&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerModeError {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机触发模式&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerModeFail {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerModeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机触发模式&quot;为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerModeIs {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerModeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机外触发源“异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerSourceError {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机外触发源“失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerSourceFail {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerSourceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;修改相机外触发源“为 的本地化字符串。
        /// </summary>
        public static string ExecuteSetTriggerSourceIs {
            get {
                return ResourceManager.GetString("ExecuteSetTriggerSourceIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行软触发一次异常 的本地化字符串。
        /// </summary>
        public static string ExecuteSoftwareTriggerError {
            get {
                return ResourceManager.GetString("ExecuteSoftwareTriggerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行软触发一次失败 的本地化字符串。
        /// </summary>
        public static string ExecuteSoftwareTriggerFail {
            get {
                return ResourceManager.GetString("ExecuteSoftwareTriggerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行软触发一次 的本地化字符串。
        /// </summary>
        public static string ExecuteSoftwareTriggerOnce {
            get {
                return ResourceManager.GetString("ExecuteSoftwareTriggerOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;开始采集&quot; 的本地化字符串。
        /// </summary>
        public static string ExecuteStartGrab {
            get {
                return ResourceManager.GetString("ExecuteStartGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;开始采集&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteStartGrabError {
            get {
                return ResourceManager.GetString("ExecuteStartGrabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;开始采集&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteStartGrabFail {
            get {
                return ResourceManager.GetString("ExecuteStartGrabFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;停止采集&quot; 的本地化字符串。
        /// </summary>
        public static string ExecuteStopGrab {
            get {
                return ResourceManager.GetString("ExecuteStopGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;停止采集&quot;异常 的本地化字符串。
        /// </summary>
        public static string ExecuteStopGrabError {
            get {
                return ResourceManager.GetString("ExecuteStopGrabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行&quot;停止采集&quot;失败 的本地化字符串。
        /// </summary>
        public static string ExecuteStopGrabFail {
            get {
                return ResourceManager.GetString("ExecuteStopGrabFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetImageFunc异常 的本地化字符串。
        /// </summary>
        public static string GetImageFuncError {
            get {
                return ResourceManager.GetString("GetImageFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取图像格式发生异常 的本地化字符串。
        /// </summary>
        public static string GetPixelFormatError {
            get {
                return ResourceManager.GetString("GetPixelFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageCallbackFun函数异常 的本地化字符串。
        /// </summary>
        public static string ImageCallbackFuncError {
            get {
                return ResourceManager.GetString("ImageCallbackFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机 的本地化字符串。
        /// </summary>
        public static string InitialCamera {
            get {
                return ResourceManager.GetString("InitialCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开相机失败,相机可能已经被占用或IP设置不正确 的本地化字符串。
        /// </summary>
        public static string OpenCameraFailReseason {
            get {
                return ResourceManager.GetString("OpenCameraFailReseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册取图回调函数失败 的本地化字符串。
        /// </summary>
        public static string RegisterCallbackFunctionFail {
            get {
                return ResourceManager.GetString("RegisterCallbackFunctionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册取图回调函数成功 的本地化字符串。
        /// </summary>
        public static string RegisterCallbackFunctionSucess {
            get {
                return ResourceManager.GetString("RegisterCallbackFunctionSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string StatueIs {
            get {
                return ResourceManager.GetString("StatueIs", resourceCulture);
            }
        }
    }
}
