<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<None Include="bin\Debug\net48\NModbus.dll" />
		<None Include="bin\Debug\net8.0-windows\NModbus.dll" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
		<PackageReference Include="NModbus" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
		<ProjectReference Include="..\Motion\Motion.csproj" />
		<ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
		<ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy $(OutDir)NModbus.dll $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\MotionPlug\$(TargetName)\ /d /y" />
		<Exec Command="xcopy $(OutDir)$(TargetFileName) $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\MotionPlug\$(TargetName)\ /d /y" />
		<Exec Command="xcopy $(OutDir)en\$(TargetName).resources.dll $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\en\ /d /y" />
	</Target>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.en.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
