//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotionControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.起始速度 的本地化字符串。
        /// </summary>
        public static string _1_起始速度 {
            get {
                return ResourceManager.GetString("1.起始速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.连接信息 的本地化字符串。
        /// </summary>
        public static string _1_连接信息 {
            get {
                return ResourceManager.GetString("1.连接信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.速度 的本地化字符串。
        /// </summary>
        public static string _1_速度 {
            get {
                return ResourceManager.GetString("1.速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.回原点 的本地化字符串。
        /// </summary>
        public static string _11_回原点 {
            get {
                return ResourceManager.GetString("11.回原点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.当前位置 的本地化字符串。
        /// </summary>
        public static string _11_当前位置 {
            get {
                return ResourceManager.GetString("11.当前位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.最佳对焦位置(mm) 的本地化字符串。
        /// </summary>
        public static string _11_最佳对焦位置_mm_ {
            get {
                return ResourceManager.GetString("11.最佳对焦位置(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.轴名称 的本地化字符串。
        /// </summary>
        public static string _11_轴名称 {
            get {
                return ResourceManager.GetString("11.轴名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.使能 的本地化字符串。
        /// </summary>
        public static string _12_使能 {
            get {
                return ResourceManager.GetString("12.使能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.正限位(mm) 的本地化字符串。
        /// </summary>
        public static string _12_正限位_mm_ {
            get {
                return ResourceManager.GetString("12.正限位(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.粗调步长(mm) 的本地化字符串。
        /// </summary>
        public static string _12_粗调步长_mm_ {
            get {
                return ResourceManager.GetString("12.粗调步长(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.绝对位置 的本地化字符串。
        /// </summary>
        public static string _12_绝对位置 {
            get {
                return ResourceManager.GetString("12.绝对位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.相对位置 的本地化字符串。
        /// </summary>
        public static string _13_相对位置 {
            get {
                return ResourceManager.GetString("13.相对位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.相对运动 的本地化字符串。
        /// </summary>
        public static string _13_相对运动 {
            get {
                return ResourceManager.GetString("13.相对运动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.精调步长(mm) 的本地化字符串。
        /// </summary>
        public static string _13_精调步长_mm_ {
            get {
                return ResourceManager.GetString("13.精调步长(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.负限位(mm) 的本地化字符串。
        /// </summary>
        public static string _13_负限位_mm_ {
            get {
                return ResourceManager.GetString("13.负限位(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.当前速度 的本地化字符串。
        /// </summary>
        public static string _14_当前速度 {
            get {
                return ResourceManager.GetString("14.当前速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.最小清晰度 的本地化字符串。
        /// </summary>
        public static string _14_最小清晰度 {
            get {
                return ResourceManager.GetString("14.最小清晰度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.绝对运动 的本地化字符串。
        /// </summary>
        public static string _14_绝对运动 {
            get {
                return ResourceManager.GetString("14.绝对运动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.运行速度(mm/s) 的本地化字符串。
        /// </summary>
        public static string _14_运行速度_mm_s_ {
            get {
                return ResourceManager.GetString("14.运行速度(mm/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15.当前扭矩 的本地化字符串。
        /// </summary>
        public static string _15_当前扭矩 {
            get {
                return ResourceManager.GetString("15.当前扭矩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15.故障复位 的本地化字符串。
        /// </summary>
        public static string _15_故障复位 {
            get {
                return ResourceManager.GetString("15.故障复位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15.精调范围(mm) 的本地化字符串。
        /// </summary>
        public static string _15_精调范围_mm_ {
            get {
                return ResourceManager.GetString("15.精调范围(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.停止运动 的本地化字符串。
        /// </summary>
        public static string _16_停止运动 {
            get {
                return ResourceManager.GetString("16.停止运动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.对焦速度(mm/s) 的本地化字符串。
        /// </summary>
        public static string _16_对焦速度_mm_s_ {
            get {
                return ResourceManager.GetString("16.对焦速度(mm/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.正限位 的本地化字符串。
        /// </summary>
        public static string _16_正限位 {
            get {
                return ResourceManager.GetString("16.正限位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17.正转 的本地化字符串。
        /// </summary>
        public static string _17_正转 {
            get {
                return ResourceManager.GetString("17.正转", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17.负限位 的本地化字符串。
        /// </summary>
        public static string _17_负限位 {
            get {
                return ResourceManager.GetString("17.负限位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18.反转 的本地化字符串。
        /// </summary>
        public static string _18_反转 {
            get {
                return ResourceManager.GetString("18.反转", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18.对焦基准位 的本地化字符串。
        /// </summary>
        public static string _18_对焦基准位 {
            get {
                return ResourceManager.GetString("18.对焦基准位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19.纠偏期望位 的本地化字符串。
        /// </summary>
        public static string _19_纠偏期望位 {
            get {
                return ResourceManager.GetString("19.纠偏期望位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19.轴报警信号 的本地化字符串。
        /// </summary>
        public static string _19_轴报警信号 {
            get {
                return ResourceManager.GetString("19.轴报警信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.加速度 的本地化字符串。
        /// </summary>
        public static string _2_加速度 {
            get {
                return ResourceManager.GetString("2.加速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.卡号 的本地化字符串。
        /// </summary>
        public static string _2_卡号 {
            get {
                return ResourceManager.GetString("2.卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.最大速度 的本地化字符串。
        /// </summary>
        public static string _2_最大速度 {
            get {
                return ResourceManager.GetString("2.最大速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.轴信息 的本地化字符串。
        /// </summary>
        public static string _2_轴信息 {
            get {
                return ResourceManager.GetString("2.轴信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.速度 的本地化字符串。
        /// </summary>
        public static string _2_速度 {
            get {
                return ResourceManager.GetString("2.速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20.纠偏感应值 的本地化字符串。
        /// </summary>
        public static string _20_纠偏感应值 {
            get {
                return ResourceManager.GetString("20.纠偏感应值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20.驱动报警信号 的本地化字符串。
        /// </summary>
        public static string _20_驱动报警信号 {
            get {
                return ResourceManager.GetString("20.驱动报警信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 21.速度 的本地化字符串。
        /// </summary>
        public static string _21_速度 {
            get {
                return ResourceManager.GetString("21.速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 22.加速度 的本地化字符串。
        /// </summary>
        public static string _22_加速度 {
            get {
                return ResourceManager.GetString("22.加速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 23.启动纠偏 的本地化字符串。
        /// </summary>
        public static string _23_启动纠偏 {
            get {
                return ResourceManager.GetString("23.启动纠偏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24.纠偏归零 的本地化字符串。
        /// </summary>
        public static string _24_纠偏归零 {
            get {
                return ResourceManager.GetString("24.纠偏归零", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.停止速度 的本地化字符串。
        /// </summary>
        public static string _3_停止速度 {
            get {
                return ResourceManager.GetString("3.停止速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.减速度 的本地化字符串。
        /// </summary>
        public static string _3_减速度 {
            get {
                return ResourceManager.GetString("3.减速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.地址信息M 的本地化字符串。
        /// </summary>
        public static string _3_地址信息M {
            get {
                return ResourceManager.GetString("3.地址信息M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.轴号 的本地化字符串。
        /// </summary>
        public static string _3_轴号 {
            get {
                return ResourceManager.GetString("3.轴号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.地址信息D 的本地化字符串。
        /// </summary>
        public static string _4_地址信息D {
            get {
                return ResourceManager.GetString("4.地址信息D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.脉冲毫米比 的本地化字符串。
        /// </summary>
        public static string _4_脉冲毫米比 {
            get {
                return ResourceManager.GetString("4.脉冲毫米比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.软限位使能 的本地化字符串。
        /// </summary>
        public static string _4_软限位使能 {
            get {
                return ResourceManager.GetString("4.软限位使能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5.对焦参数 的本地化字符串。
        /// </summary>
        public static string _5_对焦参数 {
            get {
                return ResourceManager.GetString("5.对焦参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8.回原点速度 的本地化字符串。
        /// </summary>
        public static string _8_回原点速度 {
            get {
                return ResourceManager.GetString("8.回原点速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9.二次回原点速度 的本地化字符串。
        /// </summary>
        public static string _9_二次回原点速度 {
            get {
                return ResourceManager.GetString("9.二次回原点速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对位置 的本地化字符串。
        /// </summary>
        public static string AbsPos {
            get {
                return ResourceManager.GetString("AbsPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入地址有误！ 的本地化字符串。
        /// </summary>
        public static string AddrError {
            get {
                return ResourceManager.GetString("AddrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警 的本地化字符串。
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否复位？ 的本地化字符串。
        /// </summary>
        public static string AskGoHome {
            get {
                return ResourceManager.GetString("AskGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在对焦中，是否停止对焦？ 的本地化字符串。
        /// </summary>
        public static string AskStopFocus {
            get {
                return ResourceManager.GetString("AskStopFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动对焦 的本地化字符串。
        /// </summary>
        public static string AutoFocus {
            get {
                return ResourceManager.GetString("AutoFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动配置 的本地化字符串。
        /// </summary>
        public static string AxisConfig {
            get {
                return ResourceManager.GetString("AxisConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴控制 的本地化字符串。
        /// </summary>
        public static string AxisControl {
            get {
                return ResourceManager.GetString("AxisControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除报警 的本地化字符串。
        /// </summary>
        public static string ClearAlarm {
            get {
                return ResourceManager.GetString("ClearAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗定位数据 的本地化字符串。
        /// </summary>
        public static string CoarseData {
            get {
                return ResourceManager.GetString("CoarseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动控制断开连接！ 的本地化字符串。
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置 的本地化字符串。
        /// </summary>
        public static string CurPos {
            get {
                return ResourceManager.GetString("CurPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前速度 的本地化字符串。
        /// </summary>
        public static string CurSpeed {
            get {
                return ResourceManager.GetString("CurSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前扭矩 的本地化字符串。
        /// </summary>
        public static string CurTorque {
            get {
                return ResourceManager.GetString("CurTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认是否删除？ 的本地化字符串。
        /// </summary>
        public static string DelecteAsk {
            get {
                return ResourceManager.GetString("DelecteAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度 的本地化字符串。
        /// </summary>
        public static string Distinct {
            get {
                return ResourceManager.GetString("Distinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动报警 的本地化字符串。
        /// </summary>
        public static string DriveAlarm {
            get {
                return ResourceManager.GetString("DriveAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读写元件 的本地化字符串。
        /// </summary>
        public static string ElementRW {
            get {
                return ResourceManager.GetString("ElementRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使能 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦异常！ 的本地化字符串。
        /// </summary>
        public static string ErrorFocus {
            get {
                return ResourceManager.GetString("ErrorFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件需要先暂停！ 的本地化字符串。
        /// </summary>
        public static string ErrorNeedStop {
            get {
                return ResourceManager.GetString("ErrorNeedStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有相机！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoCam {
            get {
                return ResourceManager.GetString("ErrorNoCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动控制未连接！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoConnect {
            get {
                return ResourceManager.GetString("ErrorNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开相机！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoOpenCam {
            get {
                return ResourceManager.GetString("ErrorNoOpenCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精定位数据 的本地化字符串。
        /// </summary>
        public static string FineData {
            get {
                return ResourceManager.GetString("FineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦数据 的本地化字符串。
        /// </summary>
        public static string FocusData {
            get {
                return ResourceManager.GetString("FocusData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦期望位 的本地化字符串。
        /// </summary>
        public static string FocusDst {
            get {
                return ResourceManager.GetString("FocusDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在对焦 的本地化字符串。
        /// </summary>
        public static string Focusing {
            get {
                return ResourceManager.GetString("Focusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦基准位 的本地化字符串。
        /// </summary>
        public static string FocusPos {
            get {
                return ResourceManager.GetString("FocusPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正向移动 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回原点 的本地化字符串。
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原点 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入IO 的本地化字符串。
        /// </summary>
        public static string InputIO {
            get {
                return ResourceManager.GetString("InputIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO信号 的本地化字符串。
        /// </summary>
        public static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴监视 的本地化字符串。
        /// </summary>
        public static string ObserveAxis {
            get {
                return ResourceManager.GetString("ObserveAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微调距离 的本地化字符串。
        /// </summary>
        public static string OnePos {
            get {
                return ResourceManager.GetString("OnePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常开/常闭 的本地化字符串。
        /// </summary>
        public static string OpenOrClose {
            get {
                return ResourceManager.GetString("OpenOrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴操作 的本地化字符串。
        /// </summary>
        public static string OperateAxis {
            get {
                return ResourceManager.GetString("OperateAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出IO 的本地化字符串。
        /// </summary>
        public static string OutputIO {
            get {
                return ResourceManager.GetString("OutputIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负限位 的本地化字符串。
        /// </summary>
        public static string PosLimitN {
            get {
                return ResourceManager.GetString("PosLimitN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正限位 的本地化字符串。
        /// </summary>
        public static string PosLimitP {
            get {
                return ResourceManager.GetString("PosLimitP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过正极限或负极限！ 的本地化字符串。
        /// </summary>
        public static string PosOverLimit {
            get {
                return ResourceManager.GetString("PosOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取值 的本地化字符串。
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步进距离 的本地化字符串。
        /// </summary>
        public static string RelaPos {
            get {
                return ResourceManager.GetString("RelaPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负向移动 的本地化字符串。
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠偏感应值 的本地化字符串。
        /// </summary>
        public static string SensorPos {
            get {
                return ResourceManager.GetString("SensorPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入地址不能为空！ 的本地化字符串。
        /// </summary>
        public static string SetOutputError {
            get {
                return ResourceManager.GetString("SetOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动器连接成功！ 的本地化字符串。
        /// </summary>
        public static string SuccessConnect {
            get {
                return ResourceManager.GetString("SuccessConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦完成！ 的本地化字符串。
        /// </summary>
        public static string SuccessFocus {
            get {
                return ResourceManager.GetString("SuccessFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入地址M 的本地化字符串。
        /// </summary>
        public static string WriteAddrM {
            get {
                return ResourceManager.GetString("WriteAddrM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部写入 的本地化字符串。
        /// </summary>
        public static string WriteAll {
            get {
                return ResourceManager.GetString("WriteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入值 的本地化字符串。
        /// </summary>
        public static string WriteVal {
            get {
                return ResourceManager.GetString("WriteVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        public static string 前进 {
            get {
                return ResourceManager.GetString("前进", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string 后退 {
            get {
                return ResourceManager.GetString("后退", resourceCulture);
            }
        }
    }
}
