<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
   
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\光源.png" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.IO.Ports" />
		<PackageReference Include="ValueConverters" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
	  <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resources\光源.png" />
	</ItemGroup>
</Project>
