<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm"  />
    <PackageReference Include="HandyControl" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="ValueConverters" />
  </ItemGroup>

</Project>
