<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy $(OutDir)$(TargetFileName) $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\AlgorithmPlug\$(TargetName)\ /d /y" />
		<Exec Command="xcopy $(ProjectDir)model $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\model\ /e /d /y" />
		<Exec Command="xcopy $(ProjectDir)dict $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\dict\ /e /d /y" />
		<Exec Command="xcopy $(ProjectDir)runtimes $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\runtimes\ /e /d /y" />
	</Target>

	<ItemGroup>
		<Compile Remove="bin\**" />
		<EmbeddedResource Remove="bin\**" />
		<None Remove="bin\**" />
		<Page Remove="bin\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="iTextSharp" />
	  <PackageReference Include="OpenCvSharp4.Extensions" />
	  <PackageReference Include="OpenVINO.CSharp.API" />
	  <PackageReference Include="OpenVINO.CSharp.API.Extensions" />
	  <PackageReference Include="SharpCompress" />
	  <PackageReference Include="Spire.XLS" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
		<ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="paddleocr\" />
	</ItemGroup>

</Project>
