; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "毛刺检测"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "广东威华"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\MetalBurrDetectionSys.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\Resources\logo.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "D:\本地代码仓库\毛刺检测软件\softwarelicense.rtf"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "毛刺检测"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\毛细检测软件说明书.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_NAME} ${PRODUCT_VERSION}.exe"
InstallDir "D:\Program Files\毛刺检测软件"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR\net48"
  SetOverwrite try
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\AlarmSetCtrl.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\AlgorithmDll.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\AppConfig.json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Autofac.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\BouncyCastle.Cryptography.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\CameraModule.dll"
  SetOutPath "$INSTDIR\net48\CamPlug\HIKVisionCam"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\CamPlug\HIKVisionCam\HIKVisionCam.dll"
  SetOutPath "$INSTDIR\net48\CamPlug\MindVisionCam"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\CamPlug\MindVisionCam\MindVisionCam.dll"
  SetOutPath "$INSTDIR\net48"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\CommunicationModule.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\CommunityToolkit.Mvvm.dll"
  SetOutPath "$INSTDIR\net48\ComPlug\Modbus"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ComPlug\Modbus\Modbus.dll"
  SetOutPath "$INSTDIR\net48\ComPlug\TCPIP"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ComPlug\TCPIP\TCPIP.dll"
  SetOutPath "$INSTDIR\net48\ComPlug\UDPIP"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ComPlug\UDPIP\UDPIP.dll"
  SetOutPath "$INSTDIR\net48"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\DataQuery.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\dogdnert.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\dogdnert_x64.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\dog_windows_3161259.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\dog_windows_x64_3161259.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\DotNetProjects.SVGImage.dll"
  SetOutPath "$INSTDIR\net48\en"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\AlarmSetCtrl.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\AlgorithmDll.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\CameraModule.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\CommunicationModule.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\DataQuery.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\HandyControl.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\HIKVisionCam.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\HistoryPlayback.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\MarkControl.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\MetalBurrDetectionSys.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\MindVisionCam.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\Modbus.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\MotionControl.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\MySqlOperatesApi.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\ProjProduceData.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\QualityGrade.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\SaveImageManage.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\SDFilter.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\TCPIP.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\UDPIP.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\WH.Controls.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\WH.DetectSystem.resources.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\en\WH.LightControl.resources.dll"
  SetOutPath "$INSTDIR\net48"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Google.Protobuf.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\HandyControl.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\HistoryPlayback.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\K4os.Compression.LZ4.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\K4os.Compression.LZ4.Streams.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\K4os.Hash.xxHash.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\LanguageManager.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\log4net.dll"
  SetOutPath "$INSTDIR\net48\LostImage"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\LostImage\LostImage.png"
  SetOutPath "$INSTDIR\net48"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MaociAlg.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Mapster.Core.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Mapster.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MarkControl.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MetalBurrDetectionSys.exe"
  CreateDirectory "$SMPROGRAMS\毛刺检测"
  CreateShortCut "$SMPROGRAMS\毛刺检测\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MetalBurrDetectionSys.exe.config"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Microsoft.Bcl.AsyncInterfaces.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Microsoft.Web.Administration.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Microsoft.Win32.Registry.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Microsoft.Xaml.Behaviors.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MiniEcatLib.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MotionControl.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MySql.Data.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\MySqlOperatesApi.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Newtonsoft.Json.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\NModbus.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\opencv_world490.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ProjProduceData.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\QualityGrade.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\SaveImageManage.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\SDFilter.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Buffers.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.CodeDom.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.ComponentModel.Annotations.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Configuration.ConfigurationManager.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Diagnostics.DiagnosticSource.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.IO.Pipelines.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.IO.Ports.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Memory.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Numerics.Vectors.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Reactive.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Reflection.TypeExtensions.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Runtime.CompilerServices.Unsafe.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Security.Principal.Windows.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.ServiceProcess.ServiceController.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Threading.Channels.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\System.Threading.Tasks.Extensions.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\Users.WH"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ValueConverters.Annotations.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ValueConverters.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.Controls.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.DetectSystem.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.Entity.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.LightControl.exe"

  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.RecipeCellRootBase.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\WH.RunCell.dll"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\ZstdSharp.dll"
  File "A:\毛刺检测加密\dog_windows_3161259.dll"
  File "A:\毛刺检测加密\dog_windows_x64_3161259.dll"
  File "A:\毛刺检测加密\dogdnert.dll"
  File "A:\毛刺检测加密\dogdnert_x64.dll"
  File "A:\毛刺检测加密\WH.Load.dll"
  SetOutPath "$INSTDIR\SystemConfig"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\CamConfig.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\CommConfig.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\MarkConfig.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\MotionConfig.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\MysqlParam.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\SaveImageParam.Json"
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\SystemConfig\SystemSetting.Json"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application

  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Helpbook" SEC02
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "D:\本地代码仓库\毛刺检测软件\断面毛刺检测软件\bin\Debug\net48\毛细检测软件说明书.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\毛细检测软件说明书.exe"
  Delete "$INSTDIR\SystemConfig\SystemSetting.Json"
  Delete "$INSTDIR\SystemConfig\SaveImageParam.Json"
  Delete "$INSTDIR\SystemConfig\MysqlParam.Json"
  Delete "$INSTDIR\SystemConfig\MotionConfig.Json"
  Delete "$INSTDIR\SystemConfig\MarkConfig.Json"
  Delete "$INSTDIR\SystemConfig\CommConfig.Json"
  Delete "$INSTDIR\SystemConfig\CamConfig.Json"
  Delete "$INSTDIR\net48\ZstdSharp.dll"
  Delete "$INSTDIR\net48\WH.RunCell.dll"
  Delete "$INSTDIR\net48\WH.RecipeCellRootBase.dll"
  Delete "$INSTDIR\net48\WH.Load.dll"
  Delete "$INSTDIR\net48\WH.LightControl.exe"
  Delete "$INSTDIR\net48\WH.Entity.dll"
  Delete "$INSTDIR\net48\WH.DetectSystem.dll"
  Delete "$INSTDIR\net48\WH.Controls.dll"
  Delete "$INSTDIR\net48\ValueConverters.dll"
  Delete "$INSTDIR\net48\ValueConverters.Annotations.dll"
  Delete "$INSTDIR\net48\Users.WH"
  Delete "$INSTDIR\net48\System.Threading.Tasks.Extensions.dll"
  Delete "$INSTDIR\net48\System.Threading.Channels.dll"
  Delete "$INSTDIR\net48\System.ServiceProcess.ServiceController.dll"
  Delete "$INSTDIR\net48\System.Security.Principal.Windows.dll"
  Delete "$INSTDIR\net48\System.Runtime.CompilerServices.Unsafe.dll"
  Delete "$INSTDIR\net48\System.Reflection.TypeExtensions.dll"
  Delete "$INSTDIR\net48\System.Reactive.dll"
  Delete "$INSTDIR\net48\System.Numerics.Vectors.dll"
  Delete "$INSTDIR\net48\System.Memory.dll"
  Delete "$INSTDIR\net48\System.IO.Ports.dll"
  Delete "$INSTDIR\net48\System.IO.Pipelines.dll"
  Delete "$INSTDIR\net48\System.Diagnostics.DiagnosticSource.dll"
  Delete "$INSTDIR\net48\System.Configuration.ConfigurationManager.dll"
  Delete "$INSTDIR\net48\System.ComponentModel.Annotations.dll"
  Delete "$INSTDIR\net48\System.CodeDom.dll"
  Delete "$INSTDIR\net48\System.Buffers.dll"
  Delete "$INSTDIR\net48\SDFilter.dll"
  Delete "$INSTDIR\net48\SaveImageManage.dll"
  Delete "$INSTDIR\net48\QualityGrade.dll"
  Delete "$INSTDIR\net48\ProjProduceData.dll"
  Delete "$INSTDIR\net48\opencv_world490.dll"
  Delete "$INSTDIR\net48\NModbus.dll"
  Delete "$INSTDIR\net48\Newtonsoft.Json.dll"
  Delete "$INSTDIR\net48\MySqlOperatesApi.dll"
  Delete "$INSTDIR\net48\MySql.Data.dll"
  Delete "$INSTDIR\net48\MotionControl.dll"
  Delete "$INSTDIR\net48\MiniEcatLib.dll"
  Delete "$INSTDIR\net48\Microsoft.Xaml.Behaviors.dll"
  Delete "$INSTDIR\net48\Microsoft.Win32.Registry.dll"
  Delete "$INSTDIR\net48\Microsoft.Web.Administration.dll"
  Delete "$INSTDIR\net48\Microsoft.Bcl.AsyncInterfaces.dll"
  Delete "$INSTDIR\net48\MetalBurrDetectionSys.exe.config"
  Delete "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  Delete "$INSTDIR\net48\MarkControl.dll"
  Delete "$INSTDIR\net48\Mapster.dll"
  Delete "$INSTDIR\net48\Mapster.Core.dll"
  Delete "$INSTDIR\net48\MaociAlg.dll"
  Delete "$INSTDIR\net48\LostImage\LostImage.png"
  Delete "$INSTDIR\net48\log4net.dll"
  Delete "$INSTDIR\net48\LanguageManager.dll"
  Delete "$INSTDIR\net48\K4os.Hash.xxHash.dll"
  Delete "$INSTDIR\net48\K4os.Compression.LZ4.Streams.dll"
  Delete "$INSTDIR\net48\K4os.Compression.LZ4.dll"
  Delete "$INSTDIR\net48\HistoryPlayback.dll"
  Delete "$INSTDIR\net48\HandyControl.dll"
  Delete "$INSTDIR\net48\Google.Protobuf.dll"
  Delete "$INSTDIR\net48\en\WH.LightControl.resources.dll"
  Delete "$INSTDIR\net48\en\WH.DetectSystem.resources.dll"
  Delete "$INSTDIR\net48\en\WH.Controls.resources.dll"
  Delete "$INSTDIR\net48\en\UDPIP.resources.dll"
  Delete "$INSTDIR\net48\en\TCPIP.resources.dll"
  Delete "$INSTDIR\net48\en\SDFilter.resources.dll"
  Delete "$INSTDIR\net48\en\SaveImageManage.resources.dll"
  Delete "$INSTDIR\net48\en\QualityGrade.resources.dll"
  Delete "$INSTDIR\net48\en\ProjProduceData.resources.dll"
  Delete "$INSTDIR\net48\en\MySqlOperatesApi.resources.dll"
  Delete "$INSTDIR\net48\en\MotionControl.resources.dll"
  Delete "$INSTDIR\net48\en\Modbus.resources.dll"
  Delete "$INSTDIR\net48\en\MindVisionCam.resources.dll"
  Delete "$INSTDIR\net48\en\MetalBurrDetectionSys.resources.dll"
  Delete "$INSTDIR\net48\en\MarkControl.resources.dll"
  Delete "$INSTDIR\net48\en\HistoryPlayback.resources.dll"
  Delete "$INSTDIR\net48\en\HIKVisionCam.resources.dll"
  Delete "$INSTDIR\net48\en\HandyControl.resources.dll"
  Delete "$INSTDIR\net48\en\DataQuery.resources.dll"
  Delete "$INSTDIR\net48\en\CommunicationModule.resources.dll"
  Delete "$INSTDIR\net48\en\CameraModule.resources.dll"
  Delete "$INSTDIR\net48\en\AlgorithmDll.resources.dll"
  Delete "$INSTDIR\net48\en\AlarmSetCtrl.resources.dll"
  Delete "$INSTDIR\net48\DotNetProjects.SVGImage.dll"
  Delete "$INSTDIR\net48\dog_windows_x64_3161259.dll"
  Delete "$INSTDIR\net48\dog_windows_3161259.dll"
  Delete "$INSTDIR\net48\dogdnert_x64.dll"
  Delete "$INSTDIR\net48\dogdnert.dll"
  Delete "$INSTDIR\net48\DataQuery.dll"
  Delete "$INSTDIR\net48\ComPlug\UDPIP\UDPIP.dll"
  Delete "$INSTDIR\net48\ComPlug\TCPIP\TCPIP.dll"
  Delete "$INSTDIR\net48\ComPlug\Modbus\Modbus.dll"
  Delete "$INSTDIR\net48\CommunityToolkit.Mvvm.dll"
  Delete "$INSTDIR\net48\CommunicationModule.dll"
  Delete "$INSTDIR\net48\CamPlug\MindVisionCam\MindVisionCam.dll"
  Delete "$INSTDIR\net48\CamPlug\HIKVisionCam\HIKVisionCam.dll"
  Delete "$INSTDIR\net48\CameraModule.dll"
  Delete "$INSTDIR\net48\BouncyCastle.Cryptography.dll"
  Delete "$INSTDIR\net48\Autofac.dll"
  Delete "$INSTDIR\net48\AppConfig.json"
  Delete "$INSTDIR\net48\AlgorithmDll.dll"
  Delete "$INSTDIR\net48\AlarmSetCtrl.dll"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\SystemConfig"
  RMDir "$INSTDIR\net48\LostImage"
  RMDir "$INSTDIR\net48\en"
  RMDir "$INSTDIR\net48\ComPlug\UDPIP"
  RMDir "$INSTDIR\net48\ComPlug\TCPIP"
  RMDir "$INSTDIR\net48\ComPlug\Modbus"
  RMDir "$INSTDIR\net48\CamPlug\MindVisionCam"
  RMDir "$INSTDIR\net48\CamPlug\HIKVisionCam"
  RMDir "$INSTDIR\net48"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd