; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "毛刺检测"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "广东威华"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\MetalBurrDetectionSys.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "断面毛刺检测软件\Resources\logo.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "softwarelicense.rtf"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "毛刺检测"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\毛细检测软件说明书.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_NAME}安装包 ${PRODUCT_VERSION}.exe"
InstallDir "D:\Program Files\毛刺检测软件"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR\net48"
  SetOverwrite try
  File "断面毛刺检测软件\bin\Debug\net48\*.dll"

  SetOutPath "$INSTDIR\net48\CamPlug\HIKVisionCam"
  File "断面毛刺检测软件\bin\Debug\net48\CamPlug\HIKVisionCam\*.dll"
  SetOutPath "$INSTDIR\net48\CamPlug\MindVisionCam"
  File "断面毛刺检测软件\bin\Debug\net48\CamPlug\MindVisionCam\*.dll"

  SetOutPath "$INSTDIR\net48\ComPlug\Modbus"
  File "断面毛刺检测软件\bin\Debug\net48\ComPlug\Modbus\*.dll"
  SetOutPath "$INSTDIR\net48\ComPlug\TCPIP"
  File "断面毛刺检测软件\bin\Debug\net48\ComPlug\TCPIP\*.dll"
  SetOutPath "$INSTDIR\net48\ComPlug\UDPIP"
  File "断面毛刺检测软件\bin\Debug\net48\ComPlug\UDPIP\*.dll"

  SetOutPath "$INSTDIR\net48\en"
  File "断面毛刺检测软件\bin\Debug\net48\en\*.dll"

  SetOutPath "$INSTDIR\net48\LostImage"
  File "断面毛刺检测软件\bin\Debug\net48\LostImage\*.png"
  SetOutPath "$INSTDIR\net48"
  File "断面毛刺检测软件\bin\Debug\net48\MetalBurrDetectionSys.exe"
  CreateDirectory "$SMPROGRAMS\毛刺检测"
  CreateShortCut "$SMPROGRAMS\毛刺检测\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  File "断面毛刺检测软件\bin\Debug\net48\*.config"
 
  File "断面毛刺检测软件\bin\Debug\net48\Users.WH"
  File "断面毛刺检测软件\bin\Debug\net48\WH.LightControl.exe"

  File "A:\毛刺检测加密\*.dll"
  SetOutPath "$INSTDIR\SystemConfig"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application

  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Helpbook" SEC02
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "断面毛刺检测软件\bin\Debug\net48\毛细检测软件说明书.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\net48\MetalBurrDetectionSys.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\毛细检测软件说明书.exe"
  Delete "$INSTDIR\SystemConfig\*.Json"

  Delete "$INSTDIR\net48\*.dll"

  Delete "$INSTDIR\net48\Users.WH"
   Delete "$INSTDIR\net48\*.json"
  Delete "$INSTDIR\net48\*.config"
  Delete "$INSTDIR\net48\*.exe"

  Delete "$INSTDIR\net48\LostImage\LostImage.png"
  Delete "$INSTDIR\net48\en\*.dll"
 

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\${PRODUCT_NAME} ${PRODUCT_VERSION}.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\SystemConfig"
  RMDir "$INSTDIR\net48\LostImage"
  RMDir "$INSTDIR\net48\en"
  RMDir "$INSTDIR\net48\ComPlug\UDPIP"
  RMDir "$INSTDIR\net48\ComPlug\TCPIP"
  RMDir "$INSTDIR\net48\ComPlug\Modbus"
  RMDir "$INSTDIR\net48\CamPlug\MindVisionCam"
  RMDir "$INSTDIR\net48\CamPlug\HIKVisionCam"
  RMDir "$INSTDIR\net48"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd