//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDFilter.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增缺陷 的本地化字符串。
        /// </summary>
        public static string AddDefect {
            get {
                return ResourceManager.GetString("AddDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加筛选 的本地化字符串。
        /// </summary>
        public static string AddSelect {
            get {
                return ResourceManager.GetString("AddSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法 的本地化字符串。
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤分选器 的本地化字符串。
        /// </summary>
        public static string DefectFilter {
            get {
                return ResourceManager.GetString("DefectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷名称 的本地化字符串。
        /// </summary>
        public static string DefectName {
            get {
                return ResourceManager.GetString("DefectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认是否删除？ 的本地化字符串。
        /// </summary>
        public static string DelecteAsk {
            get {
                return ResourceManager.GetString("DelecteAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻转结果 的本地化字符串。
        /// </summary>
        public static string IsReversal {
            get {
                return ResourceManager.GetString("IsReversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下限 的本地化字符串。
        /// </summary>
        public static string LowLimit {
            get {
                return ResourceManager.GetString("LowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不合法! 的本地化字符串。
        /// </summary>
        public static string NameInValid {
            get {
                return ResourceManager.GetString("NameInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空! 的本地化字符串。
        /// </summary>
        public static string NameNotNull {
            get {
                return ResourceManager.GetString("NameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称重名! 的本地化字符串。
        /// </summary>
        public static string NameRepeat {
            get {
                return ResourceManager.GetString("NameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量等级 的本地化字符串。
        /// </summary>
        public static string QualityLevel {
            get {
                return ResourceManager.GetString("QualityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分选 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示颜色 的本地化字符串。
        /// </summary>
        public static string ShowColor {
            get {
                return ResourceManager.GetString("ShowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测设置 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上限 的本地化字符串。
        /// </summary>
        public static string UpLimit {
            get {
                return ResourceManager.GetString("UpLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用下限 的本地化字符串。
        /// </summary>
        public static string UseLow {
            get {
                return ResourceManager.GetString("UseLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用上限 的本地化字符串。
        /// </summary>
        public static string UseUp {
            get {
                return ResourceManager.GetString("UseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷输出类型不同，切换后过滤分选特征需要重新设置！ 的本地化字符串。
        /// </summary>
        public static string 算法修改询问 {
            get {
                return ResourceManager.GetString("算法修改询问", resourceCulture);
            }
        }
    }
}
