<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <LangVersion>10.0</LangVersion>
    <UseWindowsForms>False</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="CameraModule\**" />
    <Compile Remove="ImageWinCtrl\**" />
    <Compile Remove="Tools\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="CameraModule\**" />
    <EmbeddedResource Remove="ImageWinCtrl\**" />
    <EmbeddedResource Remove="Tools\**" />
    <None Remove="bin\**" />
    <None Remove="CameraModule\**" />
    <None Remove="ImageWinCtrl\**" />
    <None Remove="Tools\**" />
    <Page Remove="bin\**" />
    <Page Remove="CameraModule\**" />
    <Page Remove="ImageWinCtrl\**" />
    <Page Remove="Tools\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\logo1.png" />
    <None Remove="Resources\图标\a-bangzhuzhichiwentijieda.png" />
    <None Remove="Resources\图标\a-biaoqianbiaoji.png" />
    <None Remove="Resources\图标\a-caidanliebiao.png" />
    <None Remove="Resources\图标\a-cengshunxu.png" />
    <None Remove="Resources\图标\a-chuangkoumianban.png" />
    <None Remove="Resources\图标\a-cipancunchu.png" />
    <None Remove="Resources\图标\a-ditudaohang.png" />
    <None Remove="Resources\图标\a-dunpaianquanfengxian.png" />
    <None Remove="Resources\图标\a-fengxiandunpaianquan.png" />
    <None Remove="Resources\图标\a-gongzuopaigongpaizhiweishenfen.png" />
    <None Remove="Resources\图标\a-jinggaoweixian.png" />
    <None Remove="Resources\图标\a-jingtoupaishepaizhaoxiezhenjietujieping.png" />
    <None Remove="Resources\图标\a-lajitongshanchu.png" />
    <None Remove="Resources\图标\a-locksuoanquanjiamibaohu.png" />
    <None Remove="Resources\图标\a-powerkaiguan.png" />
    <None Remove="Resources\图标\a-shezhicanshu.png" />
    <None Remove="Resources\图标\a-shezhicanshuchilun.png" />
    <None Remove="Resources\图标\a-shezhicanshupeizhi.png" />
    <None Remove="Resources\图标\a-shezhipeizhicanshu.png" />
    <None Remove="Resources\图标\a-shijianlishishijianshizhong.png" />
    <None Remove="Resources\图标\a-tianjiazengjiajiaru.png" />
    <None Remove="Resources\图标\a-tupianzhaopianxiangpian.png" />
    <None Remove="Resources\图标\a-xiangjipaishepaizhaoxiezhen.png" />
    <None Remove="Resources\图标\a-yanjingwuxiaoyincang.png" />
    <None Remove="Resources\图标\a-yanjingyouxiaodekejiande.png" />
    <None Remove="Resources\图标\a-zhuyeshouye.png" />
    <None Remove="Resources\图标\bangzhuwendang.png" />
    <None Remove="Resources\图标\beizhu.png" />
    <None Remove="Resources\图标\bijibendiannao.png" />
    <None Remove="Resources\图标\shishijiankong.png" />
    <None Remove="Resources\图标\wenbenwendangwenjian.png" />
    <None Remove="Resources\图标\主页.svg" />
    <None Remove="Resources\图标\书本知识教育.png" />
    <None Remove="Resources\图标\保存工程.svg" />
    <None Remove="Resources\图标\修改工程.svg" />
    <None Remove="Resources\图标\光源.svg" />
    <None Remove="Resources\图标\全景照片.png" />
    <None Remove="Resources\图标\关于.svg" />
    <None Remove="Resources\图标\副本复制.png" />
    <None Remove="Resources\图标\另存工程.svg" />
    <None Remove="Resources\图标\图片.svg" />
    <None Remove="Resources\图标\图片设置.svg" />
    <None Remove="Resources\图标\太阳亮度天气.png" />
    <None Remove="Resources\图标\工具.svg" />
    <None Remove="Resources\图标\工具\手动调试.svg" />
    <None Remove="Resources\图标\帮助.svg" />
    <None Remove="Resources\图标\帮助文档.svg" />
    <None Remove="Resources\图标\截屏保存.svg" />
    <None Remove="Resources\图标\打开工程.svg" />
    <None Remove="Resources\图标\拍摄拍照.png" />
    <None Remove="Resources\图标\排列方式.png" />
    <None Remove="Resources\图标\政府银行税务.png" />
    <None Remove="Resources\图标\数据清空.svg" />
    <None Remove="Resources\图标\数据监控.svg" />
    <None Remove="Resources\图标\数据监控.svg.ldenc" />
    <None Remove="Resources\图标\数据统计.svg" />
    <None Remove="Resources\图标\数据统计\数据库设置.svg" />
    <None Remove="Resources\图标\数据统计\数据查询.svg" />
    <None Remove="Resources\图标\新建工程.svg" />
    <None Remove="Resources\图标\最近打开.svg" />
    <None Remove="Resources\图标\相机.svg" />
    <None Remove="Resources\图标\相机通讯.svg" />
    <None Remove="Resources\图标\离线检测.svg" />
    <None Remove="Resources\图标\笑脸满意乐意.png" />
    <None Remove="Resources\图标\系统设置.svg" />
    <None Remove="Resources\图标\语言.svg" />
    <None Remove="Resources\图标\通讯.svg" />
    <None Remove="Resources\图标\风险盾牌安全.svg" />
    <None Remove="Resources\图片\图片管理\图片管理.png" />
    <None Remove="Resources\图片\图片管理\存图设置.png" />
    <None Remove="Resources\图片\图片管理\截屏保存.png" />
    <None Remove="Resources\图片\工具\光源.png" />
    <None Remove="Resources\图片\工具\工具.png" />
    <None Remove="Resources\图片\工具\手动调试.png" />
    <None Remove="Resources\图片\工具\离线检测.png" />
    <None Remove="Resources\图片\工具\离线测试\右播放.png" />
    <None Remove="Resources\图片\工具\离线测试\图片.png" />
    <None Remove="Resources\图片\工具\离线测试\左播放.png" />
    <None Remove="Resources\图片\工具\离线测试\当前.png" />
    <None Remove="Resources\图片\工具\离线测试\循环.png" />
    <None Remove="Resources\图片\工具\离线测试\播放2.png" />
    <None Remove="Resources\图片\工具\离线测试\文件夹.png" />
    <None Remove="Resources\图片\工具\离线测试\暂停.png" />
    <None Remove="Resources\图片\工具\离线测试\火.png" />
    <None Remove="Resources\图片\工牌职位身份.png" />
    <None Remove="Resources\图片\工程管理\主页.png" />
    <None Remove="Resources\图片\工程管理\保存工程.png" />
    <None Remove="Resources\图片\工程管理\另存工程.png" />
    <None Remove="Resources\图片\工程管理\打开工程.png" />
    <None Remove="Resources\图片\工程管理\新建工程.png" />
    <None Remove="Resources\图片\工程管理\最近打开.png" />
    <None Remove="Resources\图片\帮助\关于.png" />
    <None Remove="Resources\图片\帮助\帮助.png" />
    <None Remove="Resources\图片\帮助\帮助文档.png" />
    <None Remove="Resources\图片\数据统计\数据库设置.png" />
    <None Remove="Resources\图片\数据统计\数据查询.png" />
    <None Remove="Resources\图片\数据统计\数据清空.png" />
    <None Remove="Resources\图片\数据统计\数据监控.png" />
    <None Remove="Resources\图片\数据统计\数据统计.png" />
    <None Remove="Resources\图片\相机通讯\相机.png" />
    <None Remove="Resources\图片\相机通讯\相机通讯.png" />
    <None Remove="Resources\图片\相机通讯\通讯.png" />
    <None Remove="Resources\图片\盾牌安全风险.png" />
    <None Remove="Resources\图片\系统设置\系统设置.png" />
    <None Remove="Resources\图片\风险盾牌安全.png" />
    <None Remove="Resources\组合-2.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0-windows\MaociAlg.dll" />
    <None Include="bin\Debug\net8.0-windows\MiniEcatLib.dll" />
    <None Include="bin\Debug\net8.0-windows\opencv_world490.dll" />
    <None Include="bin\Debug\net8.0-windows\WH.LightControl.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DotNetProjects.SVGImage" />
    <PackageReference Include="HandyControl" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="ValueConverters" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\工具\手动调试.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\数据统计\数据库设置.svg" />
    <Resource Include="Resources\图标\数据统计\数据查询.svg" />
    <Resource Include="Resources\图标\文件\主页.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\打开工程.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\保存工程.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\工具\光源.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\图片设置\图片.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\图片设置\图片设置.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\帮助\关于.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\语言\语言.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\数据统计\数据清空.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\另存工程.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\数据统计\数据监控.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\工具\工具.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\帮助\帮助.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\相机通讯\相机通讯.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\数据统计\数据统计.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\帮助\帮助文档.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\最近打开.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\图片设置\截屏保存.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\新建工程.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\相机通讯\相机.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\工具\离线检测.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\系统设置\系统设置.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\文件\修改工程.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图标\相机通讯\通讯.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\图片\图片管理\图片管理.png" />
    <Resource Include="Resources\图片\图片管理\存图设置.png" />
    <Resource Include="Resources\图片\图片管理\截屏保存.png" />
    <Resource Include="Resources\图片\工具\光源.png" />
    <Resource Include="Resources\图片\工具\工具.png" />
    <Resource Include="Resources\图片\工具\手动调试.png" />
    <Resource Include="Resources\图片\工具\离线检测.png" />
    <Resource Include="Resources\图片\工具\离线测试\右播放.png" />
    <Resource Include="Resources\图片\工具\离线测试\图片.png" />
    <Resource Include="Resources\图片\工具\离线测试\左播放.png" />
    <Resource Include="Resources\图片\工具\离线测试\当前.png" />
    <Resource Include="Resources\图片\工具\离线测试\循环.png" />
    <Resource Include="Resources\图片\工具\离线测试\播放2.png" />
    <Resource Include="Resources\图片\工具\离线测试\文件夹.png" />
    <Resource Include="Resources\图片\工具\离线测试\暂停.png" />
    <Resource Include="Resources\图片\工具\离线测试\火.png" />
    <Resource Include="Resources\图片\工牌职位身份.png" />
    <Resource Include="Resources\图片\工程管理\主页.png" />
    <Resource Include="Resources\图片\工程管理\保存工程.png" />
    <Resource Include="Resources\图片\工程管理\另存工程.png" />
    <Resource Include="Resources\图片\工程管理\打开工程.png" />
    <Resource Include="Resources\图片\工程管理\新建工程.png" />
    <Resource Include="Resources\图片\工程管理\最近打开.png" />
    <Resource Include="Resources\图片\帮助\关于.png" />
    <Resource Include="Resources\图片\帮助\帮助.png" />
    <Resource Include="Resources\图片\帮助\帮助文档.png" />
    <Resource Include="Resources\图片\数据统计\数据库设置.png" />
    <Resource Include="Resources\图片\数据统计\数据查询.png" />
    <Resource Include="Resources\图片\数据统计\数据清空.png" />
    <Resource Include="Resources\图片\数据统计\数据监控.png" />
    <Resource Include="Resources\图片\数据统计\数据统计.png" />
    <Resource Include="Resources\图片\相机通讯\相机.png" />
    <Resource Include="Resources\图片\相机通讯\相机通讯.png" />
    <Resource Include="Resources\图片\相机通讯\通讯.png" />
    <Resource Include="Resources\图片\盾牌安全风险.png" />
    <Resource Include="Resources\图片\系统设置\系统设置.png" />
    <Resource Include="Resources\图片\风险盾牌安全.png" />
    <Resource Include="Resources\组合-2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\ModifyProj\ModifyProjResources.Designer.cs">
      <DependentUpon>ModifyProjResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Views\ModifyProj\ModifyProjWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\NewProj\NewProjResources.Designer.cs">
      <DependentUpon>NewProjResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Views\OfflineTest\OfflineTestResources.Designer.cs">
      <DependentUpon>OfflineTestResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Views\SystemSetting\SystemSettingResources.Designer.cs">
      <DependentUpon>SystemSettingResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Views\TimeTriggerTest\TimeTriggerTestResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TimeTriggerTestResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ModifyProj\ModifyProjResources.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>ModifyProjResources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\NewProj\NewProjResources.resx">
      <LastGenOutput>NewProjResources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\OfflineTest\OfflineTestResources.resx">
      <LastGenOutput>OfflineTestResources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\SystemSetting\SystemSettingResources.resx">
      <LastGenOutput>SystemSettingResources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\TimeTriggerTest\TimeTriggerTestResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TimeTriggerTestResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlarmSetCtrlWPF\AlarmSetCtrl.csproj" />
    <ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
    <ProjectReference Include="..\CameraModule\CameraModule.csproj" />
    <ProjectReference Include="..\CommunicationModule\CommunicationModule.csproj" />
    <ProjectReference Include="..\DataQuery\DataQuery.csproj" />
    <ProjectReference Include="..\HistoryPlayback\HistoryPlayback.csproj" />
    <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
    <ProjectReference Include="..\MarkControl\MarkControl.csproj" />
    <ProjectReference Include="..\MotionControl\MotionControl.csproj" />
    <ProjectReference Include="..\ProjProduceData\ProjProduceData.csproj" />
    <ProjectReference Include="..\MySqlOperatesApiWPF\MySqlOperatesApi.csproj" />
    <ProjectReference Include="..\QualityGrade\QualityGrade.csproj" />
    <ProjectReference Include="..\SaveImageManageWPF\SaveImageManage.csproj" />
    <ProjectReference Include="..\SDFilterCtrl\SDFilter.csproj" />
    <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
    <ProjectReference Include="..\WH.DetectSystem\WH.DetectSystem.csproj" />
    <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
    <ProjectReference Include="..\WH.RecipeCellRootBase\WH.RecipeCellRootBase.csproj" />
    <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
  </ItemGroup>

</Project>
