//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WH.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Adjust {
            get {
                return ResourceManager.GetString("Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （集合） 的本地化字符串。
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合编辑器 的本地化字符串。
        /// </summary>
        public static string CollectionEditor {
            get {
                return ResourceManager.GetString("CollectionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺员 的本地化字符串。
        /// </summary>
        public static string Craftman {
            get {
                return ResourceManager.GetString("Craftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程师 的本地化字符串。
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自适应 的本地化字符串。
        /// </summary>
        public static string FitWindow {
            get {
                return ResourceManager.GetString("FitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空,请正确输入密码 的本地化字符串。
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空,请输入用户名 的本地化字符串。
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string LoginPeriod {
            get {
                return ResourceManager.GetString("LoginPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆成功 的本地化字符串。
        /// </summary>
        public static string LoginSucceed {
            get {
                return ResourceManager.GetString("LoginSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员不可删除 的本地化字符串。
        /// </summary>
        public static string ManagerCanNotbeRemoved {
            get {
                return ResourceManager.GetString("ManagerCanNotbeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改出错: 的本地化字符串。
        /// </summary>
        public static string ModifyError {
            get {
                return ResourceManager.GetString("ModifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不正确 的本地化字符串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string PleaseInputPassword {
            get {
                return ResourceManager.GetString("PleaseInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择用户名拥有的权限 的本地化字符串。
        /// </summary>
        public static string PleaseSelectRights {
            get {
                return ResourceManager.GetString("PleaseSelectRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择用户 的本地化字符串。
        /// </summary>
        public static string PleaseSelectUser {
            get {
                return ResourceManager.GetString("PleaseSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户: 的本地化字符串。
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存图片 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录 的本地化字符串。
        /// </summary>
        public static string Unlogin {
            get {
                return ResourceManager.GetString("Unlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户名已存在 的本地化字符串。
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户设置 的本地化字符串。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户名不存在 的本地化字符串。
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
