//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveImageManage.View {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SaveimageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaveimageResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveImageManage.View.SaveimageResources", typeof(SaveimageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按制程(相机)名称存 的本地化字符串。
        /// </summary>
        public static string byCam {
            get {
                return ResourceManager.GetString("byCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按缺陷类型存 的本地化字符串。
        /// </summary>
        public static string byDefect {
            get {
                return ResourceManager.GetString("byDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按流水号存 的本地化字符串。
        /// </summary>
        public static string byID {
            get {
                return ResourceManager.GetString("byID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按小时存 的本地化字符串。
        /// </summary>
        public static string byTime {
            get {
                return ResourceManager.GetString("byTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹路径设置 的本地化字符串。
        /// </summary>
        public static string FolderSet {
            get {
                return ResourceManager.GetString("FolderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图格式 的本地化字符串。
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NG存图天数 的本地化字符串。
        /// </summary>
        public static string NGDays {
            get {
                return ResourceManager.GetString("NGDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK存图天数 的本地化字符串。
        /// </summary>
        public static string OkDays {
            get {
                return ResourceManager.GetString("OkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK间隔存图(张) 的本地化字符串。
        /// </summary>
        public static string OKIntervalCount {
            get {
                return ResourceManager.GetString("OKIntervalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK存截图 的本地化字符串。
        /// </summary>
        public static string OKScreenShot {
            get {
                return ResourceManager.GetString("OKScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存原图设置 的本地化字符串。
        /// </summary>
        public static string OriginalSet {
            get {
                return ResourceManager.GetString("OriginalSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存截图设置 的本地化字符串。
        /// </summary>
        public static string PiantImageSet {
            get {
                return ResourceManager.GetString("PiantImageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存截图 的本地化字符串。
        /// </summary>
        public static string PiantScreenEnable {
            get {
                return ResourceManager.GetString("PiantScreenEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按工程名称存 的本地化字符串。
        /// </summary>
        public static string Proj {
            get {
                return ResourceManager.GetString("Proj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存所有图片 的本地化字符串。
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存原图 的本地化字符串。
        /// </summary>
        public static string SaveImageEnable {
            get {
                return ResourceManager.GetString("SaveImageEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图设置 的本地化字符串。
        /// </summary>
        public static string SaveImageSet {
            get {
                return ResourceManager.GetString("SaveImageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存不良图片 的本地化字符串。
        /// </summary>
        public static string SaveNG {
            get {
                return ResourceManager.GetString("SaveNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存合格图片 的本地化字符串。
        /// </summary>
        public static string SaveOK {
            get {
                return ResourceManager.GetString("SaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择路径 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
    }
}
