<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CameraModule\CameraModule.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MVSDK_Net">
      <HintPath>..\packages\ThirdLocalDll\MVSDK_Net.dll</HintPath>
    </Reference>
  </ItemGroup>

	
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy $(OutDir)$(TargetFileName) $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\CamPlug\$(TargetName)\ /d /y" />
	    <Exec Command="xcopy $(OutDir)MVSDK_Net.dll $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\CamPlug\$(TargetName)\ /d /y" />
  </Target>

</Project>
