//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquidLens.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiquidLens.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 00.串口号 的本地化字符串。
        /// </summary>
        public static string _00_串口号 {
            get {
                return ResourceManager.GetString("00.串口号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00.最佳对焦位置(mm) 的本地化字符串。
        /// </summary>
        public static string _00_最佳对焦位置_mm_ {
            get {
                return ResourceManager.GetString("00.最佳对焦位置(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00.正限位(mm) 的本地化字符串。
        /// </summary>
        public static string _00_正限位_mm_ {
            get {
                return ResourceManager.GetString("00.正限位(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 01.波特率 的本地化字符串。
        /// </summary>
        public static string _01_波特率 {
            get {
                return ResourceManager.GetString("01.波特率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 01.粗调步长(mm) 的本地化字符串。
        /// </summary>
        public static string _01_粗调步长_mm_ {
            get {
                return ResourceManager.GetString("01.粗调步长(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 01.负限位(mm) 的本地化字符串。
        /// </summary>
        public static string _01_负限位_mm_ {
            get {
                return ResourceManager.GetString("01.负限位(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 02.奇偶校验 的本地化字符串。
        /// </summary>
        public static string _02_奇偶校验 {
            get {
                return ResourceManager.GetString("02.奇偶校验", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 02.精调步长(mm) 的本地化字符串。
        /// </summary>
        public static string _02_精调步长_mm_ {
            get {
                return ResourceManager.GetString("02.精调步长(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 03.数据位 的本地化字符串。
        /// </summary>
        public static string _03_数据位 {
            get {
                return ResourceManager.GetString("03.数据位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 03.最小清晰度 的本地化字符串。
        /// </summary>
        public static string _03_最小清晰度 {
            get {
                return ResourceManager.GetString("03.最小清晰度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 04.停止位 的本地化字符串。
        /// </summary>
        public static string _04_停止位 {
            get {
                return ResourceManager.GetString("04.停止位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 04.精调范围(mm) 的本地化字符串。
        /// </summary>
        public static string _04_精调范围_mm_ {
            get {
                return ResourceManager.GetString("04.精调范围(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 05.传感器位置(mm) 的本地化字符串。
        /// </summary>
        public static string _05_传感器位置_mm_ {
            get {
                return ResourceManager.GetString("05.传感器位置(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 05.握手协议 的本地化字符串。
        /// </summary>
        public static string _05_握手协议 {
            get {
                return ResourceManager.GetString("05.握手协议", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 06.从站地址 的本地化字符串。
        /// </summary>
        public static string _06_从站地址 {
            get {
                return ResourceManager.GetString("06.从站地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.液态镜头连接 的本地化字符串。
        /// </summary>
        public static string _1_液态镜头连接 {
            get {
                return ResourceManager.GetString("1.液态镜头连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.限位参数 的本地化字符串。
        /// </summary>
        public static string _2_限位参数 {
            get {
                return ResourceManager.GetString("2.限位参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.物距电压公式 的本地化字符串。
        /// </summary>
        public static string _3_物距电压公式 {
            get {
                return ResourceManager.GetString("3.物距电压公式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.传感器连接 的本地化字符串。
        /// </summary>
        public static string _4_传感器连接 {
            get {
                return ResourceManager.GetString("4.传感器连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5.对焦参数 的本地化字符串。
        /// </summary>
        public static string _5_对焦参数 {
            get {
                return ResourceManager.GetString("5.对焦参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对位置 的本地化字符串。
        /// </summary>
        public static string AbsPos {
            get {
                return ResourceManager.GetString("AbsPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对电压 的本地化字符串。
        /// </summary>
        public static string AbsVol {
            get {
                return ResourceManager.GetString("AbsVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入地址有误！ 的本地化字符串。
        /// </summary>
        public static string AddrError {
            get {
                return ResourceManager.GetString("AddrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在对焦中，是否停止对焦？ 的本地化字符串。
        /// </summary>
        public static string AskStopFocus {
            get {
                return ResourceManager.GetString("AskStopFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动对焦 的本地化字符串。
        /// </summary>
        public static string AutoFocus {
            get {
                return ResourceManager.GetString("AutoFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗定位数据 的本地化字符串。
        /// </summary>
        public static string CoarseData {
            get {
                return ResourceManager.GetString("CoarseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜头和传感器断开连接！ 的本地化字符串。
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜头断开连接！ 的本地化字符串。
        /// </summary>
        public static string ConnectErrorLens {
            get {
                return ResourceManager.GetString("ConnectErrorLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器断开连接！ 的本地化字符串。
        /// </summary>
        public static string ConnectErrorSensor {
            get {
                return ResourceManager.GetString("ConnectErrorSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制 的本地化字符串。
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置 的本地化字符串。
        /// </summary>
        public static string CurPos {
            get {
                return ResourceManager.GetString("CurPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前电压 的本地化字符串。
        /// </summary>
        public static string CurVol {
            get {
                return ResourceManager.GetString("CurVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据： 的本地化字符串。
        /// </summary>
        public static string DataRecv {
            get {
                return ResourceManager.GetString("DataRecv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据： 的本地化字符串。
        /// </summary>
        public static string DataSend {
            get {
                return ResourceManager.GetString("DataSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度 的本地化字符串。
        /// </summary>
        public static string Distinct {
            get {
                return ResourceManager.GetString("Distinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读写元件 的本地化字符串。
        /// </summary>
        public static string ElementRW {
            get {
                return ResourceManager.GetString("ElementRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦异常！ 的本地化字符串。
        /// </summary>
        public static string ErrorFocus {
            get {
                return ResourceManager.GetString("ErrorFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件需要先暂停！ 的本地化字符串。
        /// </summary>
        public static string ErrorNeedStop {
            get {
                return ResourceManager.GetString("ErrorNeedStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有相机！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoCam {
            get {
                return ResourceManager.GetString("ErrorNoCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜头未连接！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoConnect {
            get {
                return ResourceManager.GetString("ErrorNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开相机！ 的本地化字符串。
        /// </summary>
        public static string ErrorNoOpenCam {
            get {
                return ResourceManager.GetString("ErrorNoOpenCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精定位数据 的本地化字符串。
        /// </summary>
        public static string FineData {
            get {
                return ResourceManager.GetString("FineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦数据 的本地化字符串。
        /// </summary>
        public static string FocusData {
            get {
                return ResourceManager.GetString("FocusData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦期望位 的本地化字符串。
        /// </summary>
        public static string FocusDst {
            get {
                return ResourceManager.GetString("FocusDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在对焦 的本地化字符串。
        /// </summary>
        public static string Focusing {
            get {
                return ResourceManager.GetString("Focusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦基准位 的本地化字符串。
        /// </summary>
        public static string FocusPos {
            get {
                return ResourceManager.GetString("FocusPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠偏期望电压 的本地化字符串。
        /// </summary>
        public static string FocusVolDst {
            get {
                return ResourceManager.GetString("FocusVolDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正向移动 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接镜头 的本地化字符串。
        /// </summary>
        public static string LensConnect {
            get {
                return ResourceManager.GetString("LensConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接镜头 的本地化字符串。
        /// </summary>
        public static string LensConnected {
            get {
                return ResourceManager.GetString("LensConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微调距离 的本地化字符串。
        /// </summary>
        public static string OnePos {
            get {
                return ResourceManager.GetString("OnePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常开/常闭 的本地化字符串。
        /// </summary>
        public static string OpenOrClose {
            get {
                return ResourceManager.GetString("OpenOrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过正极限或负极限！ 的本地化字符串。
        /// </summary>
        public static string PosOverLimit {
            get {
                return ResourceManager.GetString("PosOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取值 的本地化字符串。
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜头电压读取失败！ 的本地化字符串。
        /// </summary>
        public static string ReadErrorLens {
            get {
                return ResourceManager.GetString("ReadErrorLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器位置读取失败! 的本地化字符串。
        /// </summary>
        public static string ReadErrorSensor {
            get {
                return ResourceManager.GetString("ReadErrorSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步进距离 的本地化字符串。
        /// </summary>
        public static string RelaPos {
            get {
                return ResourceManager.GetString("RelaPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步进电压 的本地化字符串。
        /// </summary>
        public static string RelaVol {
            get {
                return ResourceManager.GetString("RelaVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负向移动 的本地化字符串。
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接传感器 的本地化字符串。
        /// </summary>
        public static string SensorConnect {
            get {
                return ResourceManager.GetString("SensorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接传感器 的本地化字符串。
        /// </summary>
        public static string SensorConnected {
            get {
                return ResourceManager.GetString("SensorConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠偏感应值 的本地化字符串。
        /// </summary>
        public static string SensorPos {
            get {
                return ResourceManager.GetString("SensorPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入地址不能为空！ 的本地化字符串。
        /// </summary>
        public static string SetOutputError {
            get {
                return ResourceManager.GetString("SetOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜头连接成功！ 的本地化字符串。
        /// </summary>
        public static string SuccessConnect {
            get {
                return ResourceManager.GetString("SuccessConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器连接成功！ 的本地化字符串。
        /// </summary>
        public static string SuccessConnectSensor {
            get {
                return ResourceManager.GetString("SuccessConnectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对焦完成！ 的本地化字符串。
        /// </summary>
        public static string SuccessFocus {
            get {
                return ResourceManager.GetString("SuccessFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入地址M 的本地化字符串。
        /// </summary>
        public static string WriteAddrM {
            get {
                return ResourceManager.GetString("WriteAddrM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        public static string 前进 {
            get {
                return ResourceManager.GetString("前进", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string 后退 {
            get {
                return ResourceManager.GetString("后退", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动纠偏 的本地化字符串。
        /// </summary>
        public static string 启动纠偏 {
            get {
                return ResourceManager.GetString("启动纠偏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物距控制 的本地化字符串。
        /// </summary>
        public static string 物距控制 {
            get {
                return ResourceManager.GetString("物距控制", resourceCulture);
            }
        }
    }
}
