<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />
		<PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
	  <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
	  <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resource1.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource1.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resource1.en.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Resource1.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
