//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH.LightControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WH.LightControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除当前的光源控制器? 的本地化字符串。
        /// </summary>
        public static string DeleteAsk {
            get {
                return ResourceManager.GetString("DeleteAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上升沿 的本地化字符串。
        /// </summary>
        public static string 上升沿 {
            get {
                return ResourceManager.GetString("上升沿", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下降沿 的本地化字符串。
        /// </summary>
        public static string 下降沿 {
            get {
                return ResourceManager.GetString("下降沿", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低电平 的本地化字符串。
        /// </summary>
        public static string 低电平 {
            get {
                return ResourceManager.GetString("低电平", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置 的本地化字符串。
        /// </summary>
        public static string 保存配置 {
            get {
                return ResourceManager.GetString("保存配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源品牌: 的本地化字符串。
        /// </summary>
        public static string 光源品牌 {
            get {
                return ResourceManager.GetString("光源品牌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源字典为空值,请检查配置文件SystemConfig中的LightConfig.Json 文件 的本地化字符串。
        /// </summary>
        public static string 光源字典为空 {
            get {
                return ResourceManager.GetString("光源字典为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源控制 的本地化字符串。
        /// </summary>
        public static string 光源控制 {
            get {
                return ResourceManager.GetString("光源控制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本参数 的本地化字符串。
        /// </summary>
        public static string 基本参数 {
            get {
                return ResourceManager.GetString("基本参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增亮 的本地化字符串。
        /// </summary>
        public static string 增亮 {
            get {
                return ResourceManager.GetString("增亮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位名称: 的本地化字符串。
        /// </summary>
        public static string 工位名称 {
            get {
                return ResourceManager.GetString("工位名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式： 的本地化字符串。
        /// </summary>
        public static string 工作模式 {
            get {
                return ResourceManager.GetString("工作模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复出厂 的本地化字符串。
        /// </summary>
        public static string 恢复出厂 {
            get {
                return ResourceManager.GetString("恢复出厂", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string 新增 {
            get {
                return ResourceManager.GetString("新增", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string 调试 {
            get {
                return ResourceManager.GetString("调试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边沿触发： 的本地化字符串。
        /// </summary>
        public static string 边沿触发 {
            get {
                return ResourceManager.GetString("边沿触发", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接控制器 的本地化字符串。
        /// </summary>
        public static string 连接控制器 {
            get {
                return ResourceManager.GetString("连接控制器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道亮度 的本地化字符串。
        /// </summary>
        public static string 通道亮度 {
            get {
                return ResourceManager.GetString("通道亮度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高低电平： 的本地化字符串。
        /// </summary>
        public static string 高低电平 {
            get {
                return ResourceManager.GetString("高低电平", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高电平 的本地化字符串。
        /// </summary>
        public static string 高电平 {
            get {
                return ResourceManager.GetString("高电平", resourceCulture);
            }
        }
    }
}
