//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaHuaCam.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaHuaCam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.触发源 的本地化字符串。
        /// </summary>
        public static string _1_触发源 {
            get {
                return ResourceManager.GetString("1.触发源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机回调函数异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorCallBack {
            get {
                return ResourceManager.GetString("ErrorCallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机关闭发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorClose {
            get {
                return ResourceManager.GetString("ErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举相机失败！ 的本地化字符串。
        /// </summary>
        public static string ErrorEnumCam1 {
            get {
                return ResourceManager.GetString("ErrorEnumCam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取所有连接的相机出现异常: 的本地化字符串。
        /// </summary>
        public static string ErrorEnumCam2 {
            get {
                return ResourceManager.GetString("ErrorEnumCam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取相机类型&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetCamType {
            get {
                return ResourceManager.GetString("ErrorGetCamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取相机类型,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetCamType2 {
            get {
                return ResourceManager.GetString("ErrorGetCamType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取当前曝光值发生异常&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetExposureTime {
            get {
                return ResourceManager.GetString("ErrorGetExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取当前曝光值发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetExposureTime2 {
            get {
                return ResourceManager.GetString("ErrorGetExposureTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取增益值&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetGain {
            get {
                return ResourceManager.GetString("ErrorGetGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取增益值,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetGain2 {
            get {
                return ResourceManager.GetString("ErrorGetGain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取Gamma&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetGamma {
            get {
                return ResourceManager.GetString("ErrorGetGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取Gamma失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetGamma2 {
            get {
                return ResourceManager.GetString("ErrorGetGamma2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取图像高度&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetHeight {
            get {
                return ResourceManager.GetString("ErrorGetHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取图像高度,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetHeight2 {
            get {
                return ResourceManager.GetString("ErrorGetHeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取触发延时&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerDelay {
            get {
                return ResourceManager.GetString("ErrorGetTriggerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取触发延时失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerDelay2 {
            get {
                return ResourceManager.GetString("ErrorGetTriggerDelay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取触发模式&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerMode {
            get {
                return ResourceManager.GetString("ErrorGetTriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取触发模式发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerMode2 {
            get {
                return ResourceManager.GetString("ErrorGetTriggerMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取输出脉冲宽度&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerPulseWidth {
            get {
                return ResourceManager.GetString("ErrorGetTriggerPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取输出脉冲宽度失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetTriggerPulseWidth2 {
            get {
                return ResourceManager.GetString("ErrorGetTriggerPulseWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;获取图像宽度&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorGetWidth {
            get {
                return ResourceManager.GetString("ErrorGetWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机获取图像宽度,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorGetWidth2 {
            get {
                return ResourceManager.GetString("ErrorGetWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机图片格式转换函数异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorImageFunc {
            get {
                return ResourceManager.GetString("ErrorImageFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机创建相机对象失败,可能已经被占用: 的本地化字符串。
        /// </summary>
        public static string ErrorInitCam1 {
            get {
                return ResourceManager.GetString("ErrorInitCam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机出现异常: 的本地化字符串。
        /// </summary>
        public static string ErrorInitCam2 {
            get {
                return ResourceManager.GetString("ErrorInitCam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;设置曝光值&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetExposureTime {
            get {
                return ResourceManager.GetString("ErrorSetExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置曝光值发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetExposureTime2 {
            get {
                return ResourceManager.GetString("ErrorSetExposureTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;设置增益&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetGain {
            get {
                return ResourceManager.GetString("ErrorSetGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置增益失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetGain2 {
            get {
                return ResourceManager.GetString("ErrorSetGain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;设置Gamma&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetGamma {
            get {
                return ResourceManager.GetString("ErrorSetGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置Gamma失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetGamma2 {
            get {
                return ResourceManager.GetString("ErrorSetGamma2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;设置触发延时&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerDelay {
            get {
                return ResourceManager.GetString("ErrorSetTriggerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置触发延时失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerDelay2 {
            get {
                return ResourceManager.GetString("ErrorSetTriggerDelay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;设置触发模式&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerMode {
            get {
                return ResourceManager.GetString("ErrorSetTriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置触发模式发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerMode2 {
            get {
                return ResourceManager.GetString("ErrorSetTriggerMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行设置&apos;输出脉冲宽度&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerPulseWidth {
            get {
                return ResourceManager.GetString("ErrorSetTriggerPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置输出脉冲宽度失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerPulseWidth2 {
            get {
                return ResourceManager.GetString("ErrorSetTriggerPulseWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;选择触发源&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerSource {
            get {
                return ResourceManager.GetString("ErrorSetTriggerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机选择触发源发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSetTriggerSource2 {
            get {
                return ResourceManager.GetString("ErrorSetTriggerSource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;软触发一次&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorSoftWare {
            get {
                return ResourceManager.GetString("ErrorSoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机执行软触发一次发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorSoftWare2 {
            get {
                return ResourceManager.GetString("ErrorSoftWare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;开始采集&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorStart {
            get {
                return ResourceManager.GetString("ErrorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机开始采集发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorStart2 {
            get {
                return ResourceManager.GetString("ErrorStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;停止采集&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorStop {
            get {
                return ResourceManager.GetString("ErrorStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机停止采集发生异常,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorStop2 {
            get {
                return ResourceManager.GetString("ErrorStop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;加载A组相机参数&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorUserLoadParam {
            get {
                return ResourceManager.GetString("ErrorUserLoadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机加载A组相机参数失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorUserLoadParam2 {
            get {
                return ResourceManager.GetString("ErrorUserLoadParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机:执行&apos;保存A组相机参数&apos;失败,错误码: 的本地化字符串。
        /// </summary>
        public static string ErrorUserSaveParam {
            get {
                return ResourceManager.GetString("ErrorUserSaveParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机保存A组相机参数失败,序列号: 的本地化字符串。
        /// </summary>
        public static string ErrorUserSaveParam2 {
            get {
                return ResourceManager.GetString("ErrorUserSaveParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回调接收到图片: 的本地化字符串。
        /// </summary>
        public static string InfoReceImage {
            get {
                return ResourceManager.GetString("InfoReceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回调执行图像入列: 的本地化字符串。
        /// </summary>
        public static string InfoReceImage2 {
            get {
                return ResourceManager.GetString("InfoReceImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专用参数 的本地化字符串。
        /// </summary>
        public static string 专用参数 {
            get {
                return ResourceManager.GetString("专用参数", resourceCulture);
            }
        }
    }
}
