<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0-windows</TargetFrameworks>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />
		<PackageReference Include="log4net" />
		<PackageReference Include="Microsoft.CSharp" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Web.Administration" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.IO.Ports" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="ValueConverters" />
	</ItemGroup>
</Project>
