//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraModule.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CameraModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.触发源 的本地化字符串。
        /// </summary>
        public static string _1_触发源 {
            get {
                return ResourceManager.GetString("1.触发源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.是否已连接 的本地化字符串。
        /// </summary>
        public static string _11_是否已连接 {
            get {
                return ResourceManager.GetString("11.是否已连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.相机序列号 的本地化字符串。
        /// </summary>
        public static string _12_相机序列号 {
            get {
                return ResourceManager.GetString("12.相机序列号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.相机品牌 的本地化字符串。
        /// </summary>
        public static string _13_相机品牌 {
            get {
                return ResourceManager.GetString("13.相机品牌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.启用本相机 的本地化字符串。
        /// </summary>
        public static string _14_启用本相机 {
            get {
                return ResourceManager.GetString("14.启用本相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15.相机名 的本地化字符串。
        /// </summary>
        public static string _15_相机名 {
            get {
                return ResourceManager.GetString("15.相机名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.相机类型 的本地化字符串。
        /// </summary>
        public static string _16_相机类型 {
            get {
                return ResourceManager.GetString("16.相机类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17.图片旋转 的本地化字符串。
        /// </summary>
        public static string _17_图片旋转 {
            get {
                return ResourceManager.GetString("17.图片旋转", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18.图像宽度(像素) 的本地化字符串。
        /// </summary>
        public static string _18_图像宽度_像素_ {
            get {
                return ResourceManager.GetString("18.图像宽度(像素)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19.图像高度(像素) 的本地化字符串。
        /// </summary>
        public static string _19_图像高度_像素_ {
            get {
                return ResourceManager.GetString("19.图像高度(像素)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20.曝光时间(us) 的本地化字符串。
        /// </summary>
        public static string _20_曝光时间_us_ {
            get {
                return ResourceManager.GetString("20.曝光时间(us)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 21.增益 的本地化字符串。
        /// </summary>
        public static string _21_增益 {
            get {
                return ResourceManager.GetString("21.增益", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 22.启用触发 的本地化字符串。
        /// </summary>
        public static string _22_启用触发 {
            get {
                return ResourceManager.GetString("22.启用触发", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 23.触发延时 的本地化字符串。
        /// </summary>
        public static string _23_触发延时 {
            get {
                return ResourceManager.GetString("23.触发延时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24.伽马值 的本地化字符串。
        /// </summary>
        public static string _24_伽马值 {
            get {
                return ResourceManager.GetString("24.伽马值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25.像素当量(mm) 的本地化字符串。
        /// </summary>
        public static string _25_像素当量_mm_ {
            get {
                return ResourceManager.GetString("25.像素当量(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 26.单帧超时时间(ms) 的本地化字符串。
        /// </summary>
        public static string _26_单帧超时时间_ms_ {
            get {
                return ResourceManager.GetString("26.单帧超时时间(ms)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 27.触发脉冲宽度 的本地化字符串。
        /// </summary>
        public static string _27_触发脉冲宽度 {
            get {
                return ResourceManager.GetString("27.触发脉冲宽度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机列表 的本地化字符串。
        /// </summary>
        public static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置 的本地化字符串。
        /// </summary>
        public static string CameraSet {
            get {
                return ResourceManager.GetString("CameraSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机IP地址 的本地化字符串。
        /// </summary>
        public static string CamIp {
            get {
                return ResourceManager.GetString("CamIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机类型 的本地化字符串。
        /// </summary>
        public static string CamType {
            get {
                return ResourceManager.GetString("CamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续触发 的本地化字符串。
        /// </summary>
        public static string ContinuousTrig {
            get {
                return ResourceManager.GetString("ContinuousTrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭相机出现错误: 的本地化字符串。
        /// </summary>
        public static string ErrorClose {
            get {
                return ResourceManager.GetString("ErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索相机界面=&gt;关闭相机错误: 的本地化字符串。
        /// </summary>
        public static string ErrorCloseCam {
            get {
                return ResourceManager.GetString("ErrorCloseCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索相机界面=&gt;搜索相机列表出现错误: 的本地化字符串。
        /// </summary>
        public static string ErrorEnumCam {
            get {
                return ResourceManager.GetString("ErrorEnumCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发信号出队,图片入队异常: 的本地化字符串。
        /// </summary>
        public static string ErrorExportImage {
            get {
                return ResourceManager.GetString("ErrorExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索相机界面=&gt;初始化相机错误: 的本地化字符串。
        /// </summary>
        public static string ErrorInit {
            get {
                return ResourceManager.GetString("ErrorInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机出现错误: 的本地化字符串。
        /// </summary>
        public static string ErrorInit2 {
            get {
                return ResourceManager.GetString("ErrorInit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机失败 的本地化字符串。
        /// </summary>
        public static string ErrorInit3 {
            get {
                return ResourceManager.GetString("ErrorInit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现超时丢帧,准备做丢帧处理 的本地化字符串。
        /// </summary>
        public static string ErrorLostImage {
            get {
                return ResourceManager.GetString("ErrorLostImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现超时丢帧,使用异常图片替换传出,超时时间为: 的本地化字符串。
        /// </summary>
        public static string ErrorLostImage2 {
            get {
                return ResourceManager.GetString("ErrorLostImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置界面=&gt;保存相机参数出现错误: 的本地化字符串。
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置界面=&gt;显示图像出现错误: 的本地化字符串。
        /// </summary>
        public static string ErrorShowImage {
            get {
                return ResourceManager.GetString("ErrorShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索相机界面=&gt;添加相机 的本地化字符串。
        /// </summary>
        public static string InfoAddCam {
            get {
                return ResourceManager.GetString("InfoAddCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化相机成功 的本地化字符串。
        /// </summary>
        public static string InfoInit {
            get {
                return ResourceManager.GetString("InfoInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机序列号: 的本地化字符串。
        /// </summary>
        public static string InfoSerial {
            get {
                return ResourceManager.GetString("InfoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string IsUse {
            get {
                return ResourceManager.GetString("IsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设置 的本地化字符串。
        /// </summary>
        public static string ParaSet {
            get {
                return ResourceManager.GetString("ParaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号 的本地化字符串。
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软触发 的本地化字符串。
        /// </summary>
        public static string SoftWare {
            get {
                return ResourceManager.GetString("SoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止触发 的本地化字符串。
        /// </summary>
        public static string StopTrig {
            get {
                return ResourceManager.GetString("StopTrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌 的本地化字符串。
        /// </summary>
        public static string Vender {
            get {
                return ResourceManager.GetString("Vender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专用参数 的本地化字符串。
        /// </summary>
        public static string 专用参数 {
            get {
                return ResourceManager.GetString("专用参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用参数 的本地化字符串。
        /// </summary>
        public static string 通用参数 {
            get {
                return ResourceManager.GetString("通用参数", resourceCulture);
            }
        }
    }
}
