//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.卡配置 的本地化字符串。
        /// </summary>
        public static string _1_卡配置 {
            get {
                return ResourceManager.GetString("1.卡配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.一圈脉冲数 的本地化字符串。
        /// </summary>
        public static string _11_一圈脉冲数 {
            get {
                return ResourceManager.GetString("11.一圈脉冲数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.从站号 的本地化字符串。
        /// </summary>
        public static string _11_从站号 {
            get {
                return ResourceManager.GetString("11.从站号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11.打标补偿(mm) 的本地化字符串。
        /// </summary>
        public static string _11_打标补偿_mm_ {
            get {
                return ResourceManager.GetString("11.打标补偿(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.滚轮直径(mm) 的本地化字符串。
        /// </summary>
        public static string _12_滚轮直径_mm_ {
            get {
                return ResourceManager.GetString("12.滚轮直径(mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12.编码器通道 的本地化字符串。
        /// </summary>
        public static string _12_编码器通道 {
            get {
                return ResourceManager.GetString("12.编码器通道", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.毫米每脉冲 的本地化字符串。
        /// </summary>
        public static string _13_毫米每脉冲 {
            get {
                return ResourceManager.GetString("13.毫米每脉冲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.触发通道 的本地化字符串。
        /// </summary>
        public static string _13_触发通道 {
            get {
                return ResourceManager.GetString("13.触发通道", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14.编码器倍频 的本地化字符串。
        /// </summary>
        public static string _14_编码器倍频 {
            get {
                return ResourceManager.GetString("14.编码器倍频", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15.编码器计数方向 的本地化字符串。
        /// </summary>
        public static string _15_编码器计数方向 {
            get {
                return ResourceManager.GetString("15.编码器计数方向", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.触发输出模式 的本地化字符串。
        /// </summary>
        public static string _16_触发输出模式 {
            get {
                return ResourceManager.GetString("16.触发输出模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 17.触发模式 的本地化字符串。
        /// </summary>
        public static string _17_触发模式 {
            get {
                return ResourceManager.GetString("17.触发模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18.脉冲宽度(10ns) 的本地化字符串。
        /// </summary>
        public static string _18_脉冲宽度_10ns_ {
            get {
                return ResourceManager.GetString("18.脉冲宽度(10ns)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19.比较器号 的本地化字符串。
        /// </summary>
        public static string _19_比较器号 {
            get {
                return ResourceManager.GetString("19.比较器号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.打标补偿 的本地化字符串。
        /// </summary>
        public static string _2_打标补偿 {
            get {
                return ResourceManager.GetString("2.打标补偿", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.编码器信息 的本地化字符串。
        /// </summary>
        public static string _3_编码器信息 {
            get {
                return ResourceManager.GetString("3.编码器信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比较器号,0-3！ 的本地化字符串。
        /// </summary>
        public static string CmpNOInfo {
            get {
                return ResourceManager.GetString("CmpNOInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打标模块连接失败，请检查网口是否正确，模块power指示灯是否正常！ 的本地化字符串。
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚轮直径，单位mm，如60mm！ 的本地化字符串。
        /// </summary>
        public static string DiameterInfo {
            get {
                return ResourceManager.GetString("DiameterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态点表 的本地化字符串。
        /// </summary>
        public static string DynamicList {
            get {
                return ResourceManager.GetString("DynamicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器计数 的本地化字符串。
        /// </summary>
        public static string EncoderData {
            get {
                return ResourceManager.GetString("EncoderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-正向，1-反向！ 的本地化字符串。
        /// </summary>
        public static string EncoderDirInfo {
            get {
                return ResourceManager.GetString("EncoderDirInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发通道，从0开始！ 的本地化字符串。
        /// </summary>
        public static string EncoderIdInfo {
            get {
                return ResourceManager.GetString("EncoderIdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1-1倍频，2-2倍频，4-4倍频！ 的本地化字符串。
        /// </summary>
        public static string EncoderModeInfo {
            get {
                return ResourceManager.GetString("EncoderModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器设置 的本地化字符串。
        /// </summary>
        public static string EncoderSet {
            get {
                return ResourceManager.GetString("EncoderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量点测试 的本地化字符串。
        /// </summary>
        public static string ManualSet {
            get {
                return ResourceManager.GetString("ManualSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量点测试（加补偿值） 的本地化字符串。
        /// </summary>
        public static string ManualSet2 {
            get {
                return ResourceManager.GetString("ManualSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动测试点表 的本地化字符串。
        /// </summary>
        public static string ManualTest {
            get {
                return ResourceManager.GetString("ManualTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打标测试 的本地化字符串。
        /// </summary>
        public static string ManualTrig {
            get {
                return ResourceManager.GetString("ManualTrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打标配置 的本地化字符串。
        /// </summary>
        public static string MarkConfig {
            get {
                return ResourceManager.GetString("MarkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打标控制 的本地化字符串。
        /// </summary>
        public static string MarkControl {
            get {
                return ResourceManager.GetString("MarkControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个脉冲多少mm！ 的本地化字符串。
        /// </summary>
        public static string MmPerPulseInfo {
            get {
                return ResourceManager.GetString("MmPerPulseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打标补偿,单位mm！ 的本地化字符串。
        /// </summary>
        public static string OffestInfo {
            get {
                return ResourceManager.GetString("OffestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0是GPIO，1是脉冲，2是PWM！ 的本地化字符串。
        /// </summary>
        public static string OutModeInfo {
            get {
                return ResourceManager.GetString("OutModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位 的本地化字符串。
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一圈脉冲数，如500P、2000P！ 的本地化字符串。
        /// </summary>
        public static string PulsePerRoundInfo {
            get {
                return ResourceManager.GetString("PulsePerRoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试触发宽度 的本地化字符串。
        /// </summary>
        public static string PulseWidth {
            get {
                return ResourceManager.GetString("PulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉冲宽度,单位10ns！ 的本地化字符串。
        /// </summary>
        public static string PulseWidthInfo {
            get {
                return ResourceManager.GetString("PulseWidthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置触发点 的本地化字符串。
        /// </summary>
        public static string SetTriggers {
            get {
                return ResourceManager.GetString("SetTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置数值 的本地化字符串。
        /// </summary>
        public static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清零 的本地化字符串。
        /// </summary>
        public static string SetZero {
            get {
                return ResourceManager.GetString("SetZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从站号，从1开始！ 的本地化字符串。
        /// </summary>
        public static string SlaveIdInfo {
            get {
                return ResourceManager.GetString("SlaveIdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动器连接成功！ 的本地化字符串。
        /// </summary>
        public static string SuccessConnect {
            get {
                return ResourceManager.GetString("SuccessConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待触发点表 的本地化字符串。
        /// </summary>
        public static string ToBeTrigger {
            get {
                return ResourceManager.GetString("ToBeTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发计数 的本地化字符串。
        /// </summary>
        public static string TriggerData {
            get {
                return ResourceManager.GetString("TriggerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器通道，从0开始！ 的本地化字符串。
        /// </summary>
        public static string TriggerIdInfo {
            get {
                return ResourceManager.GetString("TriggerIdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-脉冲信号，1-电平翻转！ 的本地化字符串。
        /// </summary>
        public static string TrigModeInfo {
            get {
                return ResourceManager.GetString("TrigModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待触发点数 的本地化字符串。
        /// </summary>
        public static string WaitTrigCnt {
            get {
                return ResourceManager.GetString("WaitTrigCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入配置 的本地化字符串。
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
