//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 断面毛刺检测软件.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("断面毛刺检测软件.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警设置 的本地化字符串。
        /// </summary>
        public static string AlarmConfig {
            get {
                return ResourceManager.GetString("AlarmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法: 的本地化字符串。
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机与通讯 的本地化字符串。
        /// </summary>
        public static string CamCom {
            get {
                return ResourceManager.GetString("CamCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯 的本地化字符串。
        /// </summary>
        public static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据清空 的本地化字符串。
        /// </summary>
        public static string DataClear {
            get {
                return ResourceManager.GetString("DataClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据统计 的本地化字符串。
        /// </summary>
        public static string DataStatistics {
            get {
                return ResourceManager.GetString("DataStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷统计列表 的本地化字符串。
        /// </summary>
        public static string DefectList {
            get {
                return ResourceManager.GetString("DefectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测区 的本地化字符串。
        /// </summary>
        public static string DetectArea {
            get {
                return ResourceManager.GetString("DetectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测设置 的本地化字符串。
        /// </summary>
        public static string DetectConfig {
            get {
                return ResourceManager.GetString("DetectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭软件 的本地化字符串。
        /// </summary>
        public static string EnvironmentExit {
            get {
                return ResourceManager.GetString("EnvironmentExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤: 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助文档 的本地化字符串。
        /// </summary>
        public static string HelpDoc {
            get {
                return ResourceManager.GetString("HelpDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回看 的本地化字符串。
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片管理 的本地化字符串。
        /// </summary>
        public static string ImageManagement {
            get {
                return ResourceManager.GetString("ImageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图设置 的本地化字符串。
        /// </summary>
        public static string ImageSave {
            get {
                return ResourceManager.GetString("ImageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换语言 的本地化字符串。
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源控制 的本地化字符串。
        /// </summary>
        public static string LightControl {
            get {
                return ResourceManager.GetString("LightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 打标设置 的本地化字符串。
        /// </summary>
        public static string MarkConfig {
            get {
                return ResourceManager.GetString("MarkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统消息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工程 的本地化字符串。
        /// </summary>
        public static string ModifyProj {
            get {
                return ResourceManager.GetString("ModifyProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动控制 的本地化字符串。
        /// </summary>
        public static string MotionControl {
            get {
                return ResourceManager.GetString("MotionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建工程 的本地化字符串。
        /// </summary>
        public static string NewProj {
            get {
                return ResourceManager.GetString("NewProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线检测 的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开用户登录界面 的本地化字符串。
        /// </summary>
        public static string OpenedUserLogin {
            get {
                return ResourceManager.GetString("OpenedUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开失败 的本地化字符串。
        /// </summary>
        public static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开工程 的本地化字符串。
        /// </summary>
        public static string OpenProj {
            get {
                return ResourceManager.GetString("OpenProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开软件 的本地化字符串。
        /// </summary>
        public static string OpenSoftware {
            get {
                return ResourceManager.GetString("OpenSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作记录 的本地化字符串。
        /// </summary>
        public static string OperateRecord {
            get {
                return ResourceManager.GetString("OperateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程管理 的本地化字符串。
        /// </summary>
        public static string ProjManagement {
            get {
                return ResourceManager.GetString("ProjManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目路径: 的本地化字符串。
        /// </summary>
        public static string ProjPath {
            get {
                return ResourceManager.GetString("ProjPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量等级 的本地化字符串。
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近打开 的本地化字符串。
        /// </summary>
        public static string RecentProj {
            get {
                return ResourceManager.GetString("RecentProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行日志 的本地化字符串。
        /// </summary>
        public static string RuningLog {
            get {
                return ResourceManager.GetString("RuningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间 的本地化字符串。
        /// </summary>
        public static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存工程 的本地化字符串。
        /// </summary>
        public static string Saveas {
            get {
                return ResourceManager.GetString("Saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存失败 的本地化字符串。
        /// </summary>
        public static string SaveasFailed {
            get {
                return ResourceManager.GetString("SaveasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工程 的本地化字符串。
        /// </summary>
        public static string SaveProj {
            get {
                return ResourceManager.GetString("SaveProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截屏保存 的本地化字符串。
        /// </summary>
        public static string ScreenShot {
            get {
                return ResourceManager.GetString("ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据统计 的本地化字符串。
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取系统配置文件失败！ 的本地化字符串。
        /// </summary>
        public static string SystemSettingsReadFailed {
            get {
                return ResourceManager.GetString("SystemSettingsReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取系统配置文件成功！ 的本地化字符串。
        /// </summary>
        public static string SystemSettingsReadSuccess {
            get {
                return ResourceManager.GetString("SystemSettingsReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统时间 的本地化字符串。
        /// </summary>
        public static string SystemTime {
            get {
                return ResourceManager.GetString("SystemTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警日志 的本地化字符串。
        /// </summary>
        public static string WarningLog {
            get {
                return ResourceManager.GetString("WarningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 组合_2 {
            get {
                object obj = ResourceManager.GetObject("组合-2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
