<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\检测设置.png" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="HandyControl" />		
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="ValueConverters" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
	  <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
	  <ProjectReference Include="..\QualityGrade\QualityGrade.csproj" />
	  <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
	  <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
	  <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resource1.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource1.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resource1.en.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Resource1.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\检测设置.png" />
	</ItemGroup>
</Project>
