//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modbus.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modbus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.名称 的本地化字符串。
        /// </summary>
        public static string _1_名称 {
            get {
                return ResourceManager.GetString("1.名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.配置 的本地化字符串。
        /// </summary>
        public static string _1_配置 {
            get {
                return ResourceManager.GetString("1.配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.类型 的本地化字符串。
        /// </summary>
        public static string _2_类型 {
            get {
                return ResourceManager.GetString("2.类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.地址 的本地化字符串。
        /// </summary>
        public static string _3_地址 {
            get {
                return ResourceManager.GetString("3.地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.写入值 的本地化字符串。
        /// </summary>
        public static string _4_写入值 {
            get {
                return ResourceManager.GetString("4.写入值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5.描述 的本地化字符串。
        /// </summary>
        public static string _5_描述 {
            get {
                return ResourceManager.GetString("5.描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读写元件测试 的本地化字符串。
        /// </summary>
        public static string TestRW {
            get {
                return ResourceManager.GetString("TestRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入全部 的本地化字符串。
        /// </summary>
        public static string WriteAll {
            get {
                return ResourceManager.GetString("WriteAll", resourceCulture);
            }
        }
    }
}
