<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0-windows</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.Extensions" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
    <ProjectReference Include="..\WH.RecipeCellRootBase\WH.RecipeCellRootBase.csproj" />
  </ItemGroup>

</Project>
