<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy $(OutDir)$(TargetFileName) $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\AlgorithmPlug\$(TargetName)\ /d /y" />

  </Target>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
    <Page Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>C:\Program Files\MVTec\HALCON-24.05-Progress\bin\dotnet35\halcondotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
