//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPIP.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPIP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.名称 的本地化字符串。
        /// </summary>
        public static string _1_名称 {
            get {
                return ResourceManager.GetString("1.名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.基础设置 的本地化字符串。
        /// </summary>
        public static string _1_基础设置 {
            get {
                return ResourceManager.GetString("1.基础设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.本地IP 的本地化字符串。
        /// </summary>
        public static string _1_本地IP {
            get {
                return ResourceManager.GetString("1.本地IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.配置 的本地化字符串。
        /// </summary>
        public static string _1_配置 {
            get {
                return ResourceManager.GetString("1.配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.字段索引 的本地化字符串。
        /// </summary>
        public static string _2_字段索引 {
            get {
                return ResourceManager.GetString("2.字段索引", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.本地端口 的本地化字符串。
        /// </summary>
        public static string _2_本地端口 {
            get {
                return ResourceManager.GetString("2.本地端口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.字段值 的本地化字符串。
        /// </summary>
        public static string _3_字段值 {
            get {
                return ResourceManager.GetString("3.字段值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.默认转码类型 的本地化字符串。
        /// </summary>
        public static string _3_默认转码类型 {
            get {
                return ResourceManager.GetString("3.默认转码类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.字段长度 的本地化字符串。
        /// </summary>
        public static string _4_字段长度 {
            get {
                return ResourceManager.GetString("4.字段长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.默认进制转换 的本地化字符串。
        /// </summary>
        public static string _4_默认进制转换 {
            get {
                return ResourceManager.GetString("4.默认进制转换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5.转码类型 的本地化字符串。
        /// </summary>
        public static string _5_转码类型 {
            get {
                return ResourceManager.GetString("5.转码类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6.进制转换 的本地化字符串。
        /// </summary>
        public static string _6_进制转换 {
            get {
                return ResourceManager.GetString("6.进制转换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7.说明 的本地化字符串。
        /// </summary>
        public static string _7_说明 {
            get {
                return ResourceManager.GetString("7.说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯设置界面=&gt; 的本地化字符串。
        /// </summary>
        public static string CommInfo {
            get {
                return ResourceManager.GetString("CommInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯设置界面=&gt;连接远程设备出现异常: 的本地化字符串。
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ping出错, 的本地化字符串。
        /// </summary>
        public static string PingError {
            get {
                return ResourceManager.GetString("PingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯设置界面=&gt;点击执行Ping 的本地化字符串。
        /// </summary>
        public static string PingInfo {
            get {
                return ResourceManager.GetString("PingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据 的本地化字符串。
        /// </summary>
        public static string RecvData {
            get {
                return ResourceManager.GetString("RecvData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收信号转换出错: 的本地化字符串。
        /// </summary>
        public static string RecvError {
            get {
                return ResourceManager.GetString("RecvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据 的本地化字符串。
        /// </summary>
        public static string SendData {
            get {
                return ResourceManager.GetString("SendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据出错, 的本地化字符串。
        /// </summary>
        public static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯设置界面=&gt;点击发送: 的本地化字符串。
        /// </summary>
        public static string SendInfo {
            get {
                return ResourceManager.GetString("SendInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息提示 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
