<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controls\UserLogin\Imgs\logogreen.png" />
    <None Remove="Controls\UserLogin\Imgs\任务栏1.ico" />
    <None Remove="Controls\UserLogin\Imgs\任务栏2.ico" />
    <None Remove="Controls\UserLogin\Imgs\售后.png" />
    <None Remove="Controls\UserLogin\Imgs\工程师.png" />
    <None Remove="Controls\UserLogin\Imgs\工艺.png" />
    <None Remove="Controls\UserLogin\Imgs\操作员.png" />
    <None Remove="Controls\UserLogin\Imgs\未登录.png" />
    <None Remove="Controls\UserLogin\Imgs\欢迎页.png" />
    <None Remove="Controls\UserLogin\Imgs\欢迎页标.png" />
    <None Remove="Controls\UserLogin\Imgs\登录页面黑.png" />
    <None Remove="Controls\UserLogin\Imgs\管理员.png" />
    <None Remove="Controls\UserLogin\Imgs\组合-2.png" />
    <None Remove="Controls\UserLogin\Imgs\组合-3.png" />
    <None Remove="Controls\UserLogin\Imgs\经纪人管理.png" />
    <None Remove="Images\清理.png" />
    <None Remove="Resources\组合-2.png" />
    <None Remove="Resources\设置面板.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetProjects.SVGImage" />
    <PackageReference Include="HandyControl" />
	  <PackageReference Include="log4net" />
	  <PackageReference Include="CommunityToolkit.Mvvm" />
	  <PackageReference Include="Newtonsoft.Json" />
	  <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
    <ProjectReference Include="..\WH.Entity\WH.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Controls\UserLogin\Imgs\logogreen.png" />
    <Resource Include="Controls\UserLogin\Imgs\任务栏1.ico" />
    <Resource Include="Controls\UserLogin\Imgs\任务栏2.ico" />
    <Resource Include="Controls\UserLogin\Imgs\售后.png" />
    <Resource Include="Controls\UserLogin\Imgs\工程师.png" />
    <Resource Include="Controls\UserLogin\Imgs\工艺.png" />
    <Resource Include="Controls\UserLogin\Imgs\操作员.png" />
    <Resource Include="Controls\UserLogin\Imgs\未登录.png" />
    <Resource Include="Controls\UserLogin\Imgs\欢迎页.png" />
    <Resource Include="Controls\UserLogin\Imgs\欢迎页标.png" />
    <Resource Include="Controls\UserLogin\Imgs\登录页面黑.png" />
    <Resource Include="Controls\UserLogin\Imgs\管理员.png" />
    <Resource Include="Controls\UserLogin\Imgs\组合-2.png" />
    <Resource Include="Controls\UserLogin\Imgs\组合-3.png" />
    <Resource Include="Controls\UserLogin\Imgs\经纪人管理.png" />
    <Resource Include="Images\清理.png" />
    <Resource Include="Resources\组合-2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\设置面板.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\WelcomePage\WelPageResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WelPageResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Controls\WelcomePage\WelPageResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WelPageResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Controls\WelcomePage\WelPageResources.en.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
