<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="2、过滤筛选\新文件夹\**" />
    <EmbeddedResource Remove="2、过滤筛选\新文件夹\**" />
    <None Remove="2、过滤筛选\新文件夹\**" />
    <Page Remove="2、过滤筛选\新文件夹\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlarmSetCtrlWPF\AlarmSetCtrl.csproj" />
    <ProjectReference Include="..\CommunicationModule\CommunicationModule.csproj" />
    <ProjectReference Include="..\HistoryPlayback\HistoryPlayback.csproj" />
    <ProjectReference Include="..\MarkControl\MarkControl.csproj" />
    <ProjectReference Include="..\MySqlOperatesApiWPF\MySqlOperatesApi.csproj" />
    <ProjectReference Include="..\MotionControl\MotionControl.csproj" />
    <ProjectReference Include="..\ProjProduceData\ProjProduceData.csproj" />
    <ProjectReference Include="..\QualityGrade\QualityGrade.csproj" />
    <ProjectReference Include="..\SaveImageManageWPF\SaveImageManage.csproj" />
    <ProjectReference Include="..\SDFilterCtrl\SDFilter.csproj" />
    <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Autofac" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
	
		<PackageReference Include="Mapster" />
	
		<PackageReference Include="Newtonsoft.Json" />
	
		<PackageReference Include="System.Threading.Channels" />
	
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="DetectSystem\SystemSet\SystemSettingResources.Designer.cs">
	    <DependentUpon>SystemSettingResources.resx</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="DetectSystem\SystemSet\SystemSettingResources.resx">
	    <LastGenOutput>SystemSettingResources.Designer.cs</LastGenOutput>
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	</ItemGroup>
</Project>
