<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0-windows</TargetFrameworks>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="2、过滤筛选\新文件夹\**" />
    <EmbeddedResource Remove="2、过滤筛选\新文件夹\**" />
    <None Remove="2、过滤筛选\新文件夹\**" />
    <Page Remove="2、过滤筛选\新文件夹\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DetectSystem\MainModel\CProcessGroupVM.cs.ldtmp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlarmSetCtrlWPF\AlarmSetCtrl.csproj" />
    <ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
    <ProjectReference Include="..\CameraModule\CameraModule.csproj" />
    <ProjectReference Include="..\CommunicationModule\CommunicationModule.csproj" />
    <ProjectReference Include="..\FocusControl\FocusControl.csproj" />
    <ProjectReference Include="..\HistoryPlayback\HistoryPlayback.csproj" />
    <ProjectReference Include="..\MarkControl\MarkControl.csproj" />
    <ProjectReference Include="..\Motion\Motion.csproj" />
    <ProjectReference Include="..\MySqlOperatesApiWPF\MySqlOperatesApi.csproj" />
    <ProjectReference Include="..\ProjProduceData\ProjProduceData.csproj" />
    <ProjectReference Include="..\QualityGrade\QualityGrade.csproj" />
    <ProjectReference Include="..\SaveImageManageWPF\SaveImageManage.csproj" />
    <ProjectReference Include="..\SDFilterCtrl\SDFilter.csproj" />
    <ProjectReference Include="..\WH.LightControl\WH.LightControl.csproj" />
    <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
    <ProjectReference Include="..\ZipperInfo\ZipperInfo.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Autofac" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Mapster" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.Threading.Channels" />
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>
