//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmSetCtrlWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmSetCtrlWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警方式 的本地化字符串。
        /// </summary>
        public static string AlarmMode {
            get {
                return ResourceManager.GetString("AlarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警名称 的本地化字符串。
        /// </summary>
        public static string AlarmName {
            get {
                return ResourceManager.GetString("AlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警源 的本地化字符串。
        /// </summary>
        public static string AlarmSource {
            get {
                return ResourceManager.GetString("AlarmSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警类型 的本地化字符串。
        /// </summary>
        public static string AlarmType {
            get {
                return ResourceManager.GetString("AlarmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限等级 的本地化字符串。
        /// </summary>
        public static string Authoritylevel {
            get {
                return ResourceManager.GetString("Authoritylevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改 的本地化字符串。
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不良品 的本地化字符串。
        /// </summary>
        public static string DefectiveProducts {
            get {
                return ResourceManager.GetString("DefectiveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警规则 的本地化字符串。
        /// </summary>
        public static string illustrate {
            get {
                return ResourceManager.GetString("illustrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立控制 的本地化字符串。
        /// </summary>
        public static string IndependentControl {
            get {
                return ResourceManager.GetString("IndependentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否弹窗 的本地化字符串。
        /// </summary>
        public static string Popup {
            get {
                return ResourceManager.GetString("Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Recently {
            get {
                return ResourceManager.GetString("Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号 的本地化字符串。
        /// </summary>
        public static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停机信号 的本地化字符串。
        /// </summary>
        public static string StopSignal {
            get {
                return ResourceManager.GetString("StopSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间控制 的本地化字符串。
        /// </summary>
        public static string TimeControl {
            get {
                return ResourceManager.GetString("TimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总数控制 的本地化字符串。
        /// </summary>
        public static string TotalsControl {
            get {
                return ResourceManager.GetString("TotalsControl", resourceCulture);
            }
        }
    }
}
