//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 断面毛刺检测软件.Views.SystemSetting {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemSettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemSettingResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("断面毛刺检测软件.Views.SystemSetting.SystemSettingResources", typeof(SystemSettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 启用自动清零 的本地化字符串。
        /// </summary>
        internal static string AutoClear {
            get {
                return ResourceManager.GetString("AutoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用设置 的本地化字符串。
        /// </summary>
        internal static string CommonSettings {
            get {
                return ResourceManager.GetString("CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据清零设置 的本地化字符串。
        /// </summary>
        internal static string DataClearSet {
            get {
                return ResourceManager.GetString("DataClearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白班 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示帧率 的本地化字符串。
        /// </summary>
        internal static string DisplayFrameRate {
            get {
                return ResourceManager.GetString("DisplayFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        internal static string EachDay {
            get {
                return ResourceManager.GetString("EachDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每周 的本地化字符串。
        /// </summary>
        internal static string EachWeek {
            get {
                return ResourceManager.GetString("EachWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否存数据库 的本地化字符串。
        /// </summary>
        internal static string IsSaveDetectData {
            get {
                return ResourceManager.GetString("IsSaveDetectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次清零时间 的本地化字符串。
        /// </summary>
        internal static string NextClearTime {
            get {
                return ResourceManager.GetString("NextClearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜班 的本地化字符串。
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线存图和数据 的本地化字符串。
        /// </summary>
        internal static string SavePicAtOfflineMode {
            get {
                return ResourceManager.GetString("SavePicAtOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每班次 的本地化字符串。
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有缺陷 的本地化字符串。
        /// </summary>
        internal static string ShowAllDefect {
            get {
                return ResourceManager.GetString("ShowAllDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示标记图形 的本地化字符串。
        /// </summary>
        internal static string ShowDrawEdges {
            get {
                return ResourceManager.GetString("ShowDrawEdges", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 制程组分页显示 的本地化字符串。
        /// </summary>
        internal static string ShowTabControl {
            get {
                return ResourceManager.GetString("ShowTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试FPGA算法 的本地化字符串。
        /// </summary>
        internal static string TestFpgaAlgrithm {
            get {
                return ResourceManager.GetString("TestFpgaAlgrithm", resourceCulture);
            }
        }
    }
}
