//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjProduceData.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjProduceData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占所有缺陷比 的本地化字符串。
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占所有检测数比 的本地化字符串。
        /// </summary>
        public static string PercentOfAll {
            get {
                return ResourceManager.GetString("PercentOfAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不良： 的本地化字符串。
        /// </summary>
        public static string 不良 {
            get {
                return ResourceManager.GetString("不良", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总数： 的本地化字符串。
        /// </summary>
        public static string 总数 {
            get {
                return ResourceManager.GetString("总数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 良品： 的本地化字符串。
        /// </summary>
        public static string 良品 {
            get {
                return ResourceManager.GetString("良品", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 良率： 的本地化字符串。
        /// </summary>
        public static string 良率 {
            get {
                return ResourceManager.GetString("良率", resourceCulture);
            }
        }
    }
}
