//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH.DetectSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WH.DetectSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 打开失败，权限不够、托管服务未安装或缺少帮助文档 的本地化字符串。
        /// </summary>
        internal static string 帮助文档打开失败 {
            get {
                return ResourceManager.GetString("帮助文档打开失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载相机配置... 的本地化字符串。
        /// </summary>
        internal static string 正在加载相机配置 {
            get {
                return ResourceManager.GetString("正在加载相机配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载通讯配置... 的本地化字符串。
        /// </summary>
        internal static string 正在加载通讯配置 {
            get {
                return ResourceManager.GetString("正在加载通讯配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在打开。。。 的本地化字符串。
        /// </summary>
        internal static string 正在打开 {
            get {
                return ResourceManager.GetString("正在打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在更新项目列表。。。 的本地化字符串。
        /// </summary>
        internal static string 正在更新项目列表 {
            get {
                return ResourceManager.GetString("正在更新项目列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取相机参数发生异常,请检查参数表是否损坏! 的本地化字符串。
        /// </summary>
        internal static string 相机连接失败 {
            get {
                return ResourceManager.GetString("相机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接通讯失败，请检查参数表！ 的本地化字符串。
        /// </summary>
        internal static string 通讯连接失败 {
            get {
                return ResourceManager.GetString("通讯连接失败", resourceCulture);
            }
        }
    }
}
