<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy $(OutDir)$(TargetFileName) $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\AlgorithmPlug\$(TargetName)\ /d /y" />
		<!--<Exec Command="xcopy $(OutDir)MaociAlg.dll $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\AlgorithmPlug\$(TargetName)\ /d /y" />-->
		<Exec Command="xcopy $(OutDir)opencv_world490.dll $(SolutionDir)断面毛刺检测软件\bin\Debug\$(TargetFramework)\AlgorithmPlug\$(TargetName)\ /d /y" />
	</Target>

	<ItemGroup>
		<Compile Remove="bin\**" />
		<EmbeddedResource Remove="bin\**" />
		<None Remove="bin\**" />
		<Page Remove="bin\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AlgorithmDll\AlgorithmDll.csproj" />
	  <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
	</ItemGroup>

</Project>
