//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmDll.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmDll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.分组名 的本地化字符串。
        /// </summary>
        public static string _1_GroupName {
            get {
                return ResourceManager.GetString("1.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.算法参数 的本地化字符串。
        /// </summary>
        public static string _2_Algorithm {
            get {
                return ResourceManager.GetString("2.Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.判定参数 的本地化字符串。
        /// </summary>
        public static string _3_Judge {
            get {
                return ResourceManager.GetString("3.Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法参数 的本地化字符串。
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认是否删除？ 的本地化字符串。
        /// </summary>
        public static string DelecteAsk {
            get {
                return ResourceManager.GetString("DelecteAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPGA参数 的本地化字符串。
        /// </summary>
        public static string FPGAParam {
            get {
                return ResourceManager.GetString("FPGAParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判定参数 的本地化字符串。
        /// </summary>
        public static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC参数 的本地化字符串。
        /// </summary>
        public static string PCParam {
            get {
                return ResourceManager.GetString("PCParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入FPGA 的本地化字符串。
        /// </summary>
        public static string WriteFpga {
            get {
                return ResourceManager.GetString("WriteFpga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组名 的本地化字符串。
        /// </summary>
        public static string 分组名 {
            get {
                return ResourceManager.GetString("分组名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续料区厚度NG长度 ≥ 长度限制时为检测NG，上传图像。 的本地化字符串。
        /// </summary>
        public static string 料区NG连续长度说明 {
            get {
                return ResourceManager.GetString("料区NG连续长度说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层上边缘 -（料区中心+铝层位置偏移值）＞ 限制上 || （料区中心+铝层位置偏移值）- 铝层下边缘＞ 限制下时为检测NG，上传图像。 的本地化字符串。
        /// </summary>
        public static string 料区中心位置限制说明 {
            get {
                return ResourceManager.GetString("料区中心位置限制说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料区厚度(um) 的本地化字符串。
        /// </summary>
        public static string 料区厚度_um_ {
            get {
                return ResourceManager.GetString("料区厚度(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料区厚度NG连续长度限制(um) 的本地化字符串。
        /// </summary>
        public static string 料区厚度NG连续长度限制_um_ {
            get {
                return ResourceManager.GetString("料区厚度NG连续长度限制(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料区厚度限制(um) 的本地化字符串。
        /// </summary>
        public static string 料区厚度限制_um_ {
            get {
                return ResourceManager.GetString("料区厚度限制(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |实际检测厚度-料区厚度| ≥ 料区厚度限制时为料区厚度NG。 的本地化字符串。
        /// </summary>
        public static string 料区厚度限制说明 {
            get {
                return ResourceManager.GetString("料区厚度限制说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料区阈值 的本地化字符串。
        /// </summary>
        public static string 料区阈值 {
            get {
                return ResourceManager.GetString("料区阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰度≥n时判定为料区查找区域，输入范围0~255。 的本地化字符串。
        /// </summary>
        public static string 料区阈值说明 {
            get {
                return ResourceManager.GetString("料区阈值说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小清晰度 的本地化字符串。
        /// </summary>
        public static string 最小清晰度 {
            get {
                return ResourceManager.GetString("最小清晰度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低于最小清晰度时判定图像失焦。 的本地化字符串。
        /// </summary>
        public static string 最小清晰度说明 {
            get {
                return ResourceManager.GetString("最小清晰度说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间(ms) 的本地化字符串。
        /// </summary>
        public static string 超时时间_ms_ {
            get {
                return ResourceManager.GetString("超时时间(ms)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测超时时间，超时判NG，显示超时缺陷。 的本地化字符串。
        /// </summary>
        public static string 超时时间说明 {
            get {
                return ResourceManager.GetString("超时时间说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续铝层厚度NG长度 ≥ 长度限制时为检测NG，上传图像。 的本地化字符串。
        /// </summary>
        public static string 铝层NG连续长度说明 {
            get {
                return ResourceManager.GetString("铝层NG连续长度说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层位置偏移值(um) 的本地化字符串。
        /// </summary>
        public static string 铝层位置偏移值_um_ {
            get {
                return ResourceManager.GetString("铝层位置偏移值(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层厚度(um) 的本地化字符串。
        /// </summary>
        public static string 铝层厚度_um_ {
            get {
                return ResourceManager.GetString("铝层厚度(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层厚度NG连续长度限制(um) 的本地化字符串。
        /// </summary>
        public static string 铝层厚度NG连续长度限制_um_ {
            get {
                return ResourceManager.GetString("铝层厚度NG连续长度限制(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层厚度限制(um) 的本地化字符串。
        /// </summary>
        public static string 铝层厚度限制_um_ {
            get {
                return ResourceManager.GetString("铝层厚度限制(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |实际检测厚度-铝层厚度| ≥ 铝层厚度限制时为铝层厚度NG。 的本地化字符串。
        /// </summary>
        public static string 铝层厚度限制说明 {
            get {
                return ResourceManager.GetString("铝层厚度限制说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层在料区中心位置限制上(um) 的本地化字符串。
        /// </summary>
        public static string 铝层在料区中心位置限制上_um_ {
            get {
                return ResourceManager.GetString("铝层在料区中心位置限制上(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层在料区中心位置限制下(um) 的本地化字符串。
        /// </summary>
        public static string 铝层在料区中心位置限制下_um_ {
            get {
                return ResourceManager.GetString("铝层在料区中心位置限制下(um)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层自适应阈值增加值 的本地化字符串。
        /// </summary>
        public static string 铝层自适应阈值增加值 {
            get {
                return ResourceManager.GetString("铝层自适应阈值增加值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层自适应阈值=自适应矩阵计算值+自适应阈值增加值，邻域大小输入范围0~50。 的本地化字符串。
        /// </summary>
        public static string 铝层自适应阈值说明 {
            get {
                return ResourceManager.GetString("铝层自适应阈值说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层自适应阈值邻域大小 的本地化字符串。
        /// </summary>
        public static string 铝层自适应阈值邻域大小 {
            get {
                return ResourceManager.GetString("铝层自适应阈值邻域大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤矩阵内亮点数量 ≥ 数量限制时判定为铝层，邻域大小输入范围0~50。 的本地化字符串。
        /// </summary>
        public static string 铝层过滤矩阵说明 {
            get {
                return ResourceManager.GetString("铝层过滤矩阵说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层过滤矩阵邻域大小 的本地化字符串。
        /// </summary>
        public static string 铝层过滤矩阵邻域大小 {
            get {
                return ResourceManager.GetString("铝层过滤矩阵邻域大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层过滤矩阵邻域点数量限制 的本地化字符串。
        /// </summary>
        public static string 铝层过滤矩阵邻域点数量限制 {
            get {
                return ResourceManager.GetString("铝层过滤矩阵邻域点数量限制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铝层阈值 的本地化字符串。
        /// </summary>
        public static string 铝层阈值 {
            get {
                return ResourceManager.GetString("铝层阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰度≥n时判定为铝层查找区域，输入范围0~255。 的本地化字符串。
        /// </summary>
        public static string 铝层阈值说明 {
            get {
                return ResourceManager.GetString("铝层阈值说明", resourceCulture);
            }
        }
    }
}
