<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="HandyControl" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationModule\CommunicationModule.csproj" />
    <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
    <ProjectReference Include="..\Modbus\Modbus.csproj" />
    <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
  </ItemGroup>

</Project>
