<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="HandyControl" />
    <PackageReference Include="KeyBoard.WPF" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.Extensions" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
    <PackageReference Include="OpenCvSharp4.Windows" />
    <PackageReference Include="OpenVINO.CSharp.API.Extensions" />
    <PackageReference Include="OpenVINO.CSharp.API.Extensions.OpenCvSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationModule\CommunicationModule.csproj" />
    <ProjectReference Include="..\LanguageManager\LanguageManager.csproj" />
    <ProjectReference Include="..\Modbus\Modbus.csproj" />
    <ProjectReference Include="..\WH.Controls\WH.Controls.csproj" />
    <ProjectReference Include="..\WH.LightControl\WH.LightControl.csproj" />
    <ProjectReference Include="..\WH.RunCell\WH.RunCell.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\packages\ThirdLocalDll\halcondotnet.dll</HintPath>
    </Reference>
    <Reference Include="TensorRtSharp">
      <HintPath>..\packages\ThirdLocalDll\TensorRtSharp.dll</HintPath>
    </Reference>
    <Reference Include="WH.VisionLearning">
      <HintPath>..\packages\ThirdLocalDll\WH.VisionLearning.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
