//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryPlayback.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HistoryPlayback.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按缺陷 的本地化字符串。
        /// </summary>
        public static string byDefect {
            get {
                return ResourceManager.GetString("byDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只看NG 的本地化字符串。
        /// </summary>
        public static string byNG {
            get {
                return ResourceManager.GetString("byNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只看OK 的本地化字符串。
        /// </summary>
        public static string byOK {
            get {
                return ResourceManager.GetString("byOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按时间 的本地化字符串。
        /// </summary>
        public static string byTime {
            get {
                return ResourceManager.GetString("byTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷名称 的本地化字符串。
        /// </summary>
        public static string DefectName {
            get {
                return ResourceManager.GetString("DefectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流水号 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量等级 的本地化字符串。
        /// </summary>
        public static string QualityLev {
            get {
                return ResourceManager.GetString("QualityLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时 的本地化字符串。
        /// </summary>
        public static string TakeTime {
            get {
                return ResourceManager.GetString("TakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 上一张 {
            get {
                object obj = ResourceManager.GetObject("上一张", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 下一张 {
            get {
                object obj = ResourceManager.GetObject("下一张", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
